/************************************************
Seleciona as linhas que serão geradas
**************************************************/
for(var i = 0; i < linhas.length; i++){
    var linha = linhas[i];

var anaGir = getQuery();

anaGir.setParam("pPeriodo",linhas[i].getCampo("PERIODO"));
anaGir.setParam("pEmp",linhas[i].getCampo("CODEMP"));

anaGir.nativeSelect("SELECT AAA.CODPROD, CASE WHEN AAA.ANALISE_COMPRA > 0 THEN AAA.ANALISE_COMPRA ELSE 0 END AS ANALISE_GIRO FROM (SELECT DAD.CODPROD, CASE  WHEN DAD.QTD_MAX > 0 THEN DAD.QTD_MAX - DAD.ESTQ WHEN DAD.ESTQ_VEND < 0 THEN (DAD.QTD_MIN * {pPeriodo}) - DAD.QTD_INV ELSE (DAD.QTD_MIN * {pPeriodo}) - DAD.ESTQ_VEND - DAD.QTD_INV END AS ANALISE_COMPRA FROM (SELECT TTT.CODPROD, NVL(TTT.QTD_MIN,0) AS QTD_MIN, NVL(TTT.QTD_MAX,0) AS QTD_MAX, NVL(TTT.QTD_INV,0) AS QTD_INV, NVL(TTT.ESTQ,0) AS ESTQ, NVL(TTT.ESTQ - (TTT.QTD_MIN * 3),0) AS ESTQ_VEND FROM (SELECT PRO.CODPROD, CASE WHEN {pEmp} = '1' THEN PRO.AD_QTDMIN_MAT  WHEN {pEmp} = '3' THEN PRO.AD_QTDMIN_MNG  WHEN {pEmp} = '4' THEN PRO.AD_QTDMIN_PER ELSE 0 END AS QTD_MIN, CASE WHEN {pEmp} = '1' THEN PRO.AD_QTD_MAX_SP WHEN {pEmp} = '3' THEN PRO.AD_QTD_MAX_MG  WHEN {pEmp} = '4' THEN PRO.AD_QTD_MAX_PE ELSE 0 END AS QTD_MAX, INV.QTDNEG AS QTD_INV, CASE WHEN {pEmp} = '1' THEN NVL(EST.ESTQ_SP,0) WHEN {pEmp} = '3' THEN NVL(EST.ESTQ_MG,0) WHEN {pEmp} = '4' THEN NVL(EST.ESTQ_PE,0) ELSE 0 END AS ESTQ FROM TGFPRO PRO LEFT JOIN(SELECT UNI.CORG AS CODPROD, SUM(III.QTDNEG) AS QTDNEG FROM (SELECT CAB.NUNOTA, ITE.CODPROD, ITE.QTDNEG FROM TGFCAB CAB LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA WHERE CAB.CODTIPOPER = '2000' AND CAB.CODEMP = {pEmp} AND CAB.STATUSNOTA = 'L' AND CAB.PENDENTE = 'S') III LEFT JOIN (SELECT PRO.CODPROD AS CORG, PRO.DESCRPROD AS NOME_MATRIZ, PAL.CODPRODALT AS CALT FROM TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL UNION ALL SELECT PRO.CODPROD, PRO.DESCRPROD AS NOME_MATRIZ, PRO.CODPROD AS CODPRODALT FROM TGFPRO PRO WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') UNI ON UNI.CALT = III.CODPROD WHERE UNI.CORG IS NOT NULL GROUP BY UNI.CORG) INV ON PRO.CODPROD = INV.CODPROD LEFT JOIN(SELECT UNI.CORG AS CODPROD, SUM(WWW.ESTQ_MG) AS ESTQ_MG, SUM(WWW.ESTQ_SP) AS ESTQ_SP, SUM(WWW.ESTQ_PE) AS ESTQ_PE FROM(SELECT PRO.CODPROD, NVL(MG.ESTOQUE,0) AS ESTQ_MG, NVL(SP.ESTOQUE,0) AS ESTQ_SP, NVL(PE.ESTOQUE,0) AS ESTQ_PE FROM TGFPRO PRO LEFT JOIN (SELECT EST.CODPROD, SUM(EST.ESTOQUE) AS ESTOQUE FROM TGFEST EST JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL WHERE EST.ESTOQUE > '0' AND PRO.USOPROD IN ('R') AND EST.CODEMP = '3' AND EST.CODLOCAL NOT IN ('10480000','10390000','10370000','10450000','10420000','10470000','10010000','10380000','14200000','20020000','30010000','30050000','10020000','10440000','20260000','10081300','20010000','30070000','040010000') GROUP BY EST.CODPROD) MG ON MG.CODPROD = PRO.CODPROD LEFT JOIN (SELECT EST.CODPROD, SUM(EST.ESTOQUE) AS ESTOQUE FROM TGFEST EST JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL WHERE EST.ESTOQUE > '0' AND PRO.USOPROD IN ('R') AND EST.CODEMP IN ('1','2') AND EST.CODLOCAL NOT IN ('10480000','10390000','10370000','10450000','10420000','10470000','10010000','10380000','14200000','20020000','30010000','30050000','10020000','10440000','20260000','10081300','20010000','30070000','040010000') GROUP BY EST.CODPROD) SP ON SP.CODPROD = PRO.CODPROD LEFT JOIN (SELECT EST.CODPROD, SUM(EST.ESTOQUE) AS ESTOQUE FROM TGFEST EST JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL WHERE EST.ESTOQUE > '0' AND PRO.USOPROD IN ('R') AND EST.CODEMP IN ('4') AND EST.CODLOCAL NOT IN ('10480000','10390000','10370000','10450000','10420000','10470000','10010000','10380000','14200000','20020000','30010000','30050000','10020000','10440000','20260000','10081300','20010000','30070000','040010000') GROUP BY EST.CODPROD) PE ON PE.CODPROD = PRO.CODPROD WHERE PRO.USOPROD = 'R' AND SP.ESTOQUE <> '0' OR MG.ESTOQUE <> '0' OR PE.ESTOQUE <> '0') WWW LEFT JOIN (SELECT PRO.CODPROD AS CORG, PAL.CODPRODALT AS CALT FROM TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL UNION ALL SELECT PRO.CODPROD, PRO.CODPROD AS CODPRODALT FROM TGFPRO PRO WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') UNI ON WWW.CODPROD = UNI.CALT WHERE UNI.CORG IS NOT NULL GROUP BY UNI.CORG) EST ON PRO.CODPROD = EST.CODPROD WHERE  PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_EXC_SINOTRUK IS NULL AND PRO.ORIGPROD = '1' AND PRO.AD_TIP_ALT = 'M' OR PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_EXC_SINOTRUK = 'N' AND PRO.ORIGPROD = '1' AND PRO.AD_TIP_ALT = 'M') TTT) DAD) AAA");

var array = new Array();
//Execução da query dentro de um loop, ou seja, enquanto houverem resultados
while(anaGir.next()){
    //Preenchendo o array com os códigos de parceiro, por meio da função push
    array.push(anaGir.getString("CODPROD"), anaGir.getString("ANALISE_GIRO"));
}
    var k = 1;

    var tamanho = array.length;

for(var j = 0; j < tamanho; j++){

var iteLista = novaLinha("AD_ITELIS");

iteLista.setCampo("ID", linhas[i].getCampo("ID"));
iteLista.setCampo("CODPROD", array[j]);
iteLista.setCampo("QTD_AG", array[k]);

j++;
k+=2;

}
mensagem = "Foram Incluidos: " + tamanho + " produtos." + array[0] + array[1] + array[2] + array[3] + array[4] + array[5] + array[6] + array[7];

}

