/************************************************
Seleciona as linhas que serão geradas
**************************************************/
for(var i = 0; i < linhas.length; i++){
  var linha = linhas[i];

var calMinima = getQuery();

calMinima.setParam("pUF",linhas[i].getCampo("UF_P"));
calMinima.setParam("pId1",linhas[i].getCampo("ID_1"));
calMinima.setParam("pId2",linhas[i].getCampo("ID_2"));
calMinima.setParam("pId3",linhas[i].getCampo("ID_3"));
calMinima.setParam("pDias1",linhas[i].getCampo("DIAS_1"));
calMinima.setParam("pDias2",linhas[i].getCampo("DIAS_2"));
calMinima.setParam("pDias3",linhas[i].getCampo("DIAS_3"));

calMinima.nativeSelect("SELECT ANG.CODPROD, SUM(ANG.AMOSTRA_1) AS AMOSTRA_1, SUM(ANG.AMOSTRA_2) AS AMOSTRA_2, SUM(ANG.AMOSTRA_3) AS AMOSTRA_3, ROUND(SUM(ANG.MEDIA + ANG.DESV_PAD),0) AS QTD_MIN FROM (SELECT FFF.CODPROD, FFF.USOPROD, FFF.AD_COD_EX, FFF.AD_TIP_ALT, FFF.QTD_CALC1 AS AMOSTRA_1, FFF.QTD_CALC2 AS AMOSTRA_2, FFF.QTD_CALC3 AS AMOSTRA_3, FFF.MEDIA, SQRT(((POWER((FFF.QTD_CALC1 - FFF.MEDIA),2))+(POWER((FFF.QTD_CALC2 - FFF.MEDIA),2))+(POWER((FFF.QTD_CALC3 - FFF.MEDIA),2))) / (3 -1)) AS DESV_PAD FROM (SELECT DDD.CODPROD, DDD.USOPROD,  DDD.AD_COD_EX,  DDD.AD_TIP_ALT, (DDD.QTD_CALC1 + DDD.QTD_CALC2 + DDD.QTD_CALC3) / 3 AS MEDIA, DDD.QTD_CALC1, DDD.QTD_CALC2, DDD.QTD_CALC3 FROM (SELECT PRO.CODPROD, PRO.USOPROD,  PRO.AD_COD_EX,  PRO.AD_TIP_ALT, ((NVL(AAA.QTD,0) / {pDias1}) * 30) AS QTD_CALC1, ((NVL(BBB.QTD,0) / {pDias2}) * 30) AS QTD_CALC2, ((NVL(CCC.QTD,0) / {pDias3}) * 30) AS QTD_CALC3 FROM TGFPRO PRO LEFT JOIN (SELECT ITE.CODPROD, SUM (ITE.QTDNEG) AS QTD, DDD.ULT_DT, CASE  WHEN TO_DATE(DDD.ULT_DT,'dd-mm-yyyy') - TO_DATE({pId1},'dd-mm-yyyy') = 0 THEN 1 ELSE TO_DATE(DDD.ULT_DT,'dd-mm-yyyy') - TO_DATE({pId1},'dd-mm-yyyy') END AS VAR_TEMPO FROM TGFCAB CAB,TGFPRO PRO, TSIUFS UFS, (SELECT ITE.CODPROD, MAX (CAB.DTNEG) AS ULT_DT FROM TGFITE ITE, TGFCAB CAB, TSIUFS UFS WHERE ITE.NUNOTA = CAB.NUNOTA AND CAB.AD_UF = UFS.DESCRICAO AND CAB.DTNEG BETWEEN TO_DATE({pId1},'dd-mm-yyyy') AND TO_DATE({pId1},'dd-mm-yyyy') + {pDias1} AND CAB.CODTIPOPER IN ('3200','3210','3262') AND UFS.AD_GRUPO_COMPRA = {pUF} GROUP BY ITE.CODPROD) DDD, TGFITE ITE WHERE ITE.NUNOTA = CAB.NUNOTA AND CAB.AD_UF = UFS.DESCRICAO AND ITE.CODPROD = DDD.CODPROD AND PRO.CODPROD = ITE.CODPROD AND CAB.DTNEG BETWEEN TO_DATE({pId1},'dd-mm-yyyy') AND TO_DATE({pId1},'dd-mm-yyyy') + {pDias1} AND CAB.CODTIPOPER IN ('3200','3210','3262') AND UFS.AD_GRUPO_COMPRA = {pUF} GROUP BY ITE.CODPROD, PRO.DESCRPROD, DDD.ULT_DT) AAA ON PRO.CODPROD = AAA.CODPROD LEFT JOIN (SELECT ITE.CODPROD, PRO.DESCRPROD, SUM (ITE.QTDNEG) AS QTD, DDD.ULT_DT, CASE  WHEN TO_DATE(DDD.ULT_DT,'dd-mm-yyyy') - TO_DATE({pId2},'dd-mm-yyyy') = 0 THEN 1 ELSE TO_DATE(DDD.ULT_DT,'dd-mm-yyyy') - TO_DATE({pId2},'dd-mm-yyyy') END AS VAR_TEMPO FROM TGFCAB CAB,TGFPRO PRO, TSIUFS UFS, (SELECT ITE.CODPROD, MAX (CAB.DTNEG) AS ULT_DT FROM TGFITE ITE, TGFCAB CAB, TSIUFS UFS WHERE ITE.NUNOTA = CAB.NUNOTA AND CAB.AD_UF = UFS.DESCRICAO AND CAB.DTNEG BETWEEN TO_DATE({pId2},'dd-mm-yyyy') AND TO_DATE({pId2},'dd-mm-yyyy') + {pDias2} AND CAB.CODTIPOPER IN ('3200','3210','3262') AND UFS.AD_GRUPO_COMPRA = {pUF} GROUP BY ITE.CODPROD) DDD, TGFITE ITE WHERE ITE.NUNOTA = CAB.NUNOTA AND CAB.AD_UF = UFS.DESCRICAO AND ITE.CODPROD = DDD.CODPROD AND PRO.CODPROD = ITE.CODPROD AND CAB.DTNEG BETWEEN TO_DATE({pId2},'dd-mm-yyyy') AND TO_DATE({pId2},'dd-mm-yyyy') + {pDias2} AND CAB.CODTIPOPER IN ('3200','3210','3262') AND UFS.AD_GRUPO_COMPRA = {pUF} GROUP BY ITE.CODPROD, PRO.DESCRPROD, DDD.ULT_DT) BBB ON PRO.CODPROD = BBB.CODPROD LEFT JOIN (SELECT ITE.CODPROD, PRO.DESCRPROD, SUM (ITE.QTDNEG) AS QTD, DDD.ULT_DT, CASE  WHEN TO_DATE(DDD.ULT_DT,'dd-mm-yyyy') - TO_DATE({pId3},'dd-mm-yyyy') = 0 THEN 1 ELSE TO_DATE(DDD.ULT_DT,'dd-mm-yyyy') - TO_DATE({pId3},'dd-mm-yyyy') END AS VAR_TEMPO FROM TGFCAB CAB,TGFPRO PRO, TSIUFS UFS, (SELECT ITE.CODPROD, MAX (CAB.DTNEG) AS ULT_DT FROM TGFITE ITE, TGFCAB CAB, TSIUFS UFS WHERE ITE.NUNOTA = CAB.NUNOTA AND CAB.AD_UF = UFS.DESCRICAO AND CAB.DTNEG BETWEEN TO_DATE({pId3},'dd-mm-yyyy') AND TO_DATE({pId3},'dd-mm-yyyy') + {pDias3} AND CAB.CODTIPOPER IN ('3200','3210','3262') AND UFS.AD_GRUPO_COMPRA = {pUF} GROUP BY ITE.CODPROD) DDD, TGFITE ITE WHERE ITE.NUNOTA = CAB.NUNOTA AND CAB.AD_UF = UFS.DESCRICAO AND ITE.CODPROD = DDD.CODPROD AND PRO.CODPROD = ITE.CODPROD AND CAB.DTNEG BETWEEN TO_DATE({pId3},'dd-mm-yyyy') AND TO_DATE({pId3},'dd-mm-yyyy') + {pDias3} AND CAB.CODTIPOPER IN ('3200','3210','3262') AND UFS.AD_GRUPO_COMPRA = {pUF} GROUP BY ITE.CODPROD, PRO.DESCRPROD, DDD.ULT_DT) CCC ON PRO.CODPROD = CCC.CODPROD WHERE PRO.USOPROD = 'R' AND PRO.ATIVO = 'S' AND PRO.AD_COD_EX IS NULL) DDD) FFF) ANG LEFT JOIN (SELECT PRO.CODPROD AS MATRIZ, PAL.CODPRODALT FROM TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL UNION ALL SELECT PRO.CODPROD, PRO.CODPROD AS CODPRODALT FROM TGFPRO PRO WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') UNI ON ANG.CODPROD = UNI.CODPRODALT WHERE ANG.USOPROD = 'R' AND ANG.AD_COD_EX IS NULL AND ANG.AD_TIP_ALT = 'M' GROUP BY ANG.CODPROD");

var array = new Array();
//Execução da query dentro de um loop, ou seja, enquanto houverem resultados
while(calMinima.next()){
//Preenchendo o array com os resultaados da query, por meio da função push
  array.push(calMinima.getString("CODPROD"), calMinima.getString("AMOSTRA_1"), calMinima.getString("AMOSTRA_2"), calMinima.getString("AMOSTRA_3"), calMinima.getString("QTD_MIN"));
}
  var k = 1;
  var l = 2;
  var m = 3;
  var n = 4;

  var tamanho = array.length;

for(var j = 0; j < tamanho; j++){

var qtdMinima = novaLinha("AD_ITEMIN");

qtdMinima.setCampo("ID", linhas[i].getCampo("ID"));
qtdMinima.setCampo("CODPROD", array[j]);
qtdMinima.setCampo("AMO_1", array[k]);
qtdMinima.setCampo("AMO_2", array[l]);
qtdMinima.setCampo("AMO_3", array[m]);
qtdMinima.setCampo("QTD_MIN", array[n]);

j+=4;
k+=5;
l+=5;
m+=5;
n+=5;

}
mensagem = "Foram Incluidos: " + (tamanho / 5) + " produtos.";

}