#type.sql# 
SELECT
CASE 
WHEN BBB.ACAO > '0' THEN 'ACAO'
WHEN BBB.PROT > '0' THEN 'PROTESTADO'
ELSE 'OK' END AS STATUS

FROM
(SELECT
OKK.CODPARC,
OKK.SIT AS OK,
ACA.SIT AS ACAO,
PPP.SIT AS PROT

FROM
(SELECT
AAA.CODPARC,
COUNT (AAA.SITUACAO) AS SIT
FROM
(SELECT
FIN.CODPARC,
CASE
WHEN FIN.AD_TIT_ACJ = 'S' THEN 'A'
WHEN FIN.AD_TIT_PROT = 'S' THEN 'P'
WHEN FIN.AD_TIT_PROT IS NULL OR FIN.AD_TIT_PROT = 'N' AND FIN.AD_TIT_ACJ = 'N' OR FIN.AD_TIT_ACJ IS NULL THEN 'K' END AS SITUACAO
FROM
TGFFIN FIN) AAA
WHERE
AAA.SITUACAO = 'K'
GROUP BY
AAA.CODPARC) OKK

FULL OUTER JOIN (SELECT
AAA.CODPARC,
COUNT (AAA.SITUACAO) AS SIT
FROM
(SELECT
FIN.CODPARC,
CASE
WHEN FIN.AD_TIT_ACJ = 'S' THEN 'A'
WHEN FIN.AD_TIT_PROT = 'S' THEN 'P'
WHEN FIN.AD_TIT_PROT IS NULL OR FIN.AD_TIT_PROT = 'N' AND FIN.AD_TIT_ACJ = 'N' OR FIN.AD_TIT_ACJ IS NULL THEN 'K' END AS SITUACAO
FROM
TGFFIN FIN) AAA
WHERE
AAA.SITUACAO = 'A'
GROUP BY
AAA.CODPARC) ACA ON OKK.CODPARC = ACA.CODPARC

FULL OUTER JOIN (SELECT
AAA.CODPARC,
COUNT (AAA.SITUACAO) AS SIT
FROM
(SELECT
FIN.CODPARC,
CASE
WHEN FIN.AD_TIT_ACJ = 'S' THEN 'A'
WHEN FIN.AD_TIT_PROT = 'S' THEN 'P'
WHEN FIN.AD_TIT_PROT IS NULL OR FIN.AD_TIT_PROT = 'N' AND FIN.AD_TIT_ACJ = 'N' OR FIN.AD_TIT_ACJ IS NULL THEN 'K' END AS SITUACAO
FROM
TGFFIN FIN) AAA
WHERE
AAA.SITUACAO = 'P'
GROUP BY
AAA.CODPARC) PPP ON OKK.CODPARC = PPP.CODPARC) BBB

WHERE
BBB.CODPARC = TGFFIN.CODPARC 

