CREATE OR REPLACE FUNCTION "SNK_GET_ORIGEM_PRODUTO_ALT" ( P_CODPROD INT,P_CODEMP INT, P_CODLOCALORIG INT, P_CONTROLE VARCHAR2)
RETURN VARCHAR2 IS

P_ORIGPROD VARCHAR2(1);

BEGIN

    SELECT CASE 
    WHEN EST.CONTROLE LIKE 'O0%' THEN '0'
    WHEN EST.CONTROLE LIKE 'O1%' THEN '1'
    WHEN EST.CONTROLE LIKE 'O2%' THEN '2'
    WHEN EST.CONTROLE LIKE 'O3%' THEN '3'
    WHEN EST.CONTROLE LIKE 'O4%' THEN '4'
    WHEN EST.CONTROLE LIKE 'O5%' THEN '5'
    WHEN EST.CONTROLE LIKE 'O6%' THEN '6'
    WHEN EST.CONTROLE LIKE 'O7%' THEN '7'
    WHEN EST.CONTROLE LIKE 'O8%' THEN '8'
    ELSE NULL
    END INTO P_ORIGPROD
    FROM TGFEST EST 
    WHERE EST.CODPROD = P_CODPROD AND EST.CONTROLE = P_CONTROLE AND EST.CODEMP = P_CODEMP AND EST.CODLOCAL = P_CODLOCALORIG;

    RETURN P_ORIGPROD;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;

END;


/