SELECT
AAA.CODPROD,
AAA.DESCRPROD,
AAA.QTD_MIN,
CASE WHEN AAA.ANALISE_COMPRA > 0 THEN AAA.ANALISE_COMPRA
ELSE 0 END AS ANALISE_GIRO,
NVL((CURRENT_DATE - DTC.DTNEG), 0) AS DIAS_SCOMPRA,
CASE WHEN (CURRENT_DATE - DTC.DTNEG) > 180 THEN 'RED'
WHEN (CURRENT_DATE - DTC.DTNEG) IS NULL THEN 'ORANGE'
ELSE 'GREEN' END AS ALERTA,
AAA.AD_ABC

FROM
(SELECT
DAD.AD_ABC,
DAD.CODPROD,
DAD.DESCRPROD,
DAD.QTD_MIN,
DAD.QTD_MAX,
DAD.QTD_INV,
DAD.ESTQ,
DAD.ESTQ_VEND,
CASE 
WHEN DAD.QTD_MAX > 0 THEN DAD.QTD_MAX - DAD.ESTQ
WHEN DAD.ESTQ_VEND < 0 THEN (DAD.QTD_MIN * :P_PERIODO) - DAD.QTD_INV
ELSE (DAD.QTD_MIN * :P_PERIODO) - DAD.ESTQ_VEND - DAD.QTD_INV END AS ANALISE_COMPRA

FROM
(SELECT
TTT.AD_ABC,
TTT.CODPROD,
TTT.DESCRPROD,
NVL(TTT.QTD_MIN,0) AS QTD_MIN,
NVL(TTT.QTD_MAX,0) AS QTD_MAX,
NVL(TTT.QTD_INV,0) AS QTD_INV,
NVL(TTT.ESTQ,0) AS ESTQ,
NVL(TTT.ESTQ - (TTT.QTD_MIN * 3),0) AS ESTQ_VEND
FROM
    (SELECT
    PRO.AD_ABC,
    PRO.CODPROD,
    PRO.DESCRPROD,
    CASE
    WHEN :P_EMP = '1' THEN MIN.SP_1
    WHEN :P_EMP = '3' THEN MIN.MG_2
    WHEN :P_EMP = '4' THEN MIN.PE_3
    ELSE 0 END AS QTD_MIN,
    CASE
    WHEN :P_EMP = '1' THEN MAX.MXSP_1
    WHEN :P_EMP = '3' THEN MAX.MXMG_2
    WHEN :P_EMP = '4' THEN MAX.MXPE_3
    ELSE 0 END AS QTD_MAX,
    INV.QTDNEG AS QTD_INV,
    CASE
    WHEN :P_EMP = '1' THEN NVL(EST.ESTQ_SP,0)
    WHEN :P_EMP = '3' THEN NVL(EST.ESTQ_MG,0)
    WHEN :P_EMP = '4' THEN NVL(EST.ESTQ_PE,0)
    ELSE 0 END AS ESTQ

    FROM
    TGFPRO PRO

    /************************************************
    Consulta de quantidades Minimas
    ************************************************/
    LEFT JOIN    (SELECT
        PRO.CODPROD,
        PRO.AD_QTDMIN_MAT AS SP_1,
        PRO.AD_QTDMIN_MNG AS MG_2,
        PRO.AD_QTDMIN_PER AS PE_3
        FROM
        TGFPRO PRO
        WHERE
        PRO.USOPROD = 'R'
        AND PRO.AD_COD_EX IS NULL
        AND PRO.ATIVO = 'S') MIN ON PRO.CODPROD = MIN.CODPROD

    /************************************************
    Consulta de quantidades Maximas
    ************************************************/
    LEFT JOIN    (SELECT
        PRO.CODPROD,
        PRO.AD_QTD_MAX_SP AS MXSP_1,
        PRO.AD_QTD_MAX_MG AS MXMG_2,
        PRO.AD_QTD_MAX_PE AS MXPE_3
        FROM
        TGFPRO PRO
        WHERE
        PRO.USOPROD = 'R'
        AND PRO.AD_COD_EX IS NULL
        AND PRO.ATIVO = 'S') MAX ON PRO.CODPROD = MAX.CODPROD

    /************************************************
    Consulta de produtos em Invoices pendentes
    ************************************************/
    LEFT JOIN    (SELECT UNI.CORG AS CODPROD, SUM(III.QTDNEG) AS QTDNEG
        FROM (SELECT CAB.NUNOTA, ITE.CODPROD, ITE.QTDNEG
            FROM TGFCAB CAB LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
            WHERE CAB.CODTIPOPER = '2000' AND CAB.CODEMP = :P_EMP AND CAB.STATUSNOTA = 'L' AND CAB.PENDENTE = 'S') III
        LEFT JOIN (SELECT PRO.CODPROD AS CORG, PRO.DESCRPROD AS NOME_MATRIZ, PAL.CODPRODALT AS CALT
            FROM TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
            WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL
            UNION ALL SELECT PRO.CODPROD, PRO.DESCRPROD AS NOME_MATRIZ, PRO.CODPROD AS CODPRODALT
            FROM TGFPRO PRO WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') UNI ON UNI.CALT = III.CODPROD
        WHERE UNI.CORG IS NOT NULL GROUP BY UNI.CORG) INV ON PRO.CODPROD = INV.CODPROD

    /************************************************
    Consulta de produtos em Estoque
    ************************************************/
    LEFT JOIN    (SELECT
        UNI.CORG AS CODPROD,
        UNI.NOME_MATRIZ AS DESCRPROD,
        SUM(WWW.ESTQ_MG) AS ESTQ_MG,
        SUM(WWW.ESTQ_SP) AS ESTQ_SP,
        SUM(WWW.ESTQ_PE) AS ESTQ_PE
        FROM    (SELECT
                PRO.CODPROD,
                PRO.DESCRPROD,
                NVL(MG.ESTOQUE,0) AS ESTQ_MG,
                NVL(SP.ESTOQUE,0) AS ESTQ_SP,
                NVL(PE.ESTOQUE,0) AS ESTQ_PE
                FROM TGFPRO PRO
                LEFT JOIN (SELECT
                    EST.CODPROD,
                    PRO.DESCRPROD AS DESCRICAO,
                    SUM(EST.ESTOQUE) AS ESTOQUE
                    FROM TGFEST EST
                    JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
                    JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL
                    WHERE EST.ESTOQUE > '0' AND PRO.USOPROD IN ('R') AND EST.CODEMP = '3'
                    AND EST.CODLOCAL NOT IN ('10480000','10390000','10370000','10450000','10420000','10470000','10010000','10380000','14200000','20020000','30010000','30050000','10020000','10440000','20260000','10081300','20010000','30070000','040010000')
                    GROUP BY EST.CODPROD, PRO.DESCRPROD) MG ON MG.CODPROD = PRO.CODPROD
                LEFT JOIN (SELECT
                    EST.CODPROD,
                    PRO.DESCRPROD AS DESCRICAO,
                    SUM(EST.ESTOQUE) AS ESTOQUE
                    FROM TGFEST EST
                    JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
                    JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL
                    WHERE EST.ESTOQUE > '0' AND PRO.USOPROD IN ('R') AND EST.CODEMP IN ('1','2')
                    AND EST.CODLOCAL NOT IN ('10480000','10390000','10370000','10450000','10420000','10470000','10010000','10380000','14200000','20020000','30010000','30050000','10020000','10440000','20260000','10081300','20010000','30070000','040010000')
                    GROUP BY EST.CODPROD, PRO.DESCRPROD) SP ON SP.CODPROD = PRO.CODPROD
                LEFT JOIN (SELECT
                    EST.CODPROD,
                    PRO.DESCRPROD AS DESCRICAO,
                    SUM(EST.ESTOQUE) AS ESTOQUE
                    FROM TGFEST EST
                    JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
                    JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL
                    WHERE EST.ESTOQUE > '0' AND PRO.USOPROD IN ('R') AND EST.CODEMP IN ('4')
                    AND EST.CODLOCAL NOT IN ('10480000','10390000','10370000','10450000','10420000','10470000','10010000','10380000','14200000','20020000','30010000','30050000','10020000','10440000','20260000','10081300','20010000','30070000','040010000')
                    GROUP BY EST.CODPROD, PRO.DESCRPROD) PE ON PE.CODPROD = PRO.CODPROD
                WHERE PRO.USOPROD = 'R' AND SP.ESTOQUE <> '0' OR MG.ESTOQUE <> '0' OR PE.ESTOQUE <> '0') WWW
        LEFT JOIN (SELECT PRO.CODPROD AS CORG, PRO.DESCRPROD AS NOME_MATRIZ, PAL.CODPRODALT AS CALT
        FROM TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
        WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL
        UNION ALL SELECT PRO.CODPROD, PRO.DESCRPROD AS NOME_MATRIZ, PRO.CODPROD AS CODPRODALT
        FROM TGFPRO PRO WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') UNI ON WWW.CODPROD = UNI.CALT
        WHERE UNI.CORG IS NOT NULL
        GROUP BY UNI.CORG, UNI.NOME_MATRIZ) EST ON PRO.CODPROD = EST.CODPROD

    WHERE 
    PRO.USOPROD = 'R'
    AND PRO.AD_COD_EX IS NULL
    AND PRO.AD_EXC_SINOTRUK IS NULL
    AND PRO.ORIGPROD = '1'
    AND PRO.AD_TIP_ALT = 'M'
    OR PRO.USOPROD = 'R'
    AND PRO.AD_COD_EX IS NULL
    AND PRO.AD_EXC_SINOTRUK = 'N'
    AND PRO.ORIGPROD = '1'
    AND PRO.AD_TIP_ALT = 'M') TTT) DAD) AAA

/************************************************
Busca a ultima data de Compra do Produto
************************************************/
LEFT JOIN (SELECT UNI.CORG AS CODPROD, MAX(DDT.DTNEG) AS DTNEG
    FROM (SELECT ITE.CODPROD, MAX (CAB.DTNEG) AS DTNEG
        FROM TGFITE ITE LEFT JOIN TGFCAB CAB ON ITE.NUNOTA =  CAB.NUNOTA
        WHERE CAB.CODTIPOPER IN ('2106') GROUP BY ITE.CODPROD) DDT
    LEFT JOIN (SELECT PRO.CODPROD AS CORG, PRO.DESCRPROD AS NOME_MATRIZ, PAL.CODPRODALT AS CALT
        FROM TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
        WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL
        UNION ALL SELECT PRO.CODPROD, PRO.DESCRPROD AS NOME_MATRIZ, PRO.CODPROD AS CODPRODALT
        FROM TGFPRO PRO WHERE PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') UNI ON UNI.CALT = DDT.CODPROD
    WHERE UNI.CORG IS NOT NULL GROUP BY UNI.CORG ) DTC ON AAA.CODPROD = DTC.CODPROD