SELECT
PRO.CODPROD,
PRO.DESCRPROD,
PRO.AD_QTDMIN_MAT,
PRO.AD_QTDMIN_MNG,
(NVL(SJC.EST_SJC,0) + NVL(SJCA.EST_SJC,0)) AS EST_SJC,
(NVL(EMG.EST_MG,0) + NVL(EMGA.EST_MG,0)) AS EST_MG,
(NVL(SJC.EST_SJC,0) + NVL(SJCA.EST_SJC,0) - NVL(PRO.AD_QTDMIN_MAT,0)) AS REST_SJC,
(NVL(EMG.EST_MG,0) + NVL(EMGA.EST_MG,0) - NVL(PRO.AD_QTDMIN_MNG,0)) AS REST_MG,
CASE
WHEN (SJC.EST_SJC - PRO.AD_QTDMIN_MAT) <= '0' OR (EMG.EST_MG - PRO.AD_QTDMIN_MNG) <= '0' THEN 'RED'
ELSE 'GREEN' END AS ALERTA

FROM
TGFPRO PRO
LEFT JOIN TGFPAL PAL ON PRO.CODPROD = PAL.CODPROD


LEFT JOIN (SELECT
EST.CODPROD,
SUM(EST.ESTOQUE) AS EST_SJC
FROM TGFEST EST
WHERE
EST.CODEMP IN ('1','2')
GROUP BY
EST.CODPROD) SJCA ON SJCA.CODPROD = PAL.CODPRODALT 
LEFT JOIN (SELECT
EST.CODPROD,
SUM(EST.ESTOQUE) AS EST_SJC
FROM TGFEST EST
WHERE
EST.CODEMP IN ('1','2')
GROUP BY
EST.CODPROD) SJC ON SJC.CODPROD = PRO.CODPROD 


LEFT JOIN (SELECT
EST.CODPROD,
SUM(EST.ESTOQUE) AS EST_MG
FROM TGFEST EST
WHERE
EST.CODEMP IN ('3')
GROUP BY
EST.CODPROD) EMG ON EMG.CODPROD = PRO.CODPROD 
LEFT JOIN (SELECT
EST.CODPROD,
SUM(EST.ESTOQUE) AS EST_MG
FROM TGFEST EST
WHERE
EST.CODEMP IN ('3')
GROUP BY
EST.CODPROD) EMGA ON EMGA.CODPROD = PAL.CODPRODALT 


WHERE
PRO.USOPROD IN ('2','V') AND PRO.CODPROD <> '0'




