SELECT
LMP.CODPRODPA,
LMP.CODPRODMP,
PRO.DESCRPROD,
DECODE(PRO.USOPROD,'2','PI','M','MP') AS USOPROD,
LMP.QTDMISTURA AS UTILIZADO,
(LMP.QTDMISTURA * :QTD) AS NECESSIDADE,
NVL(QTD.ESTOQUE,0) AS ESTOQUE,
(NVL(QTD.ESTOQUE,0) - (LMP.QTDMISTURA * :QTD)) AS SALDO

FROM
TPRLMP LMP
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = LMP.CODPRODMP
LEFT JOIN (SELECT
MAX(LMP.IDEFX) AS PROCESSO,
LMP.CODPRODPA AS PRODIDX
FROM
TPRLMP LMP
GROUP BY
LMP.CODPRODPA) IDX ON LMP.CODPRODPA = IDX.PRODIDX
LEFT JOIN (SELECT
EST.CODPROD,
SUM(EST.ESTOQUE) AS ESTOQUE
FROM TGFEST EST
WHERE EST.CODEMP = '2' AND EST.CODLOCAL = '010390000'
GROUP BY EST.CODPROD
) QTD ON LMP.CODPRODMP = QTD.CODPROD

WHERE
LMP.CODPRODPA = :PROD
AND LMP.IDEFX = IDX.PROCESSO


