SELECT
ANG.CODPROD,
ANG.DESCRPROD,
ANG.AMOSTRA_1,
ANG.AMOSTRA_2,
ANG.AMOSTRA_3,
ANG.MEDIA,
ANG.DESV_PAD,
ANG.MEDIA + ANG.DESV_PAD AS QTD_MIN

FROM
(SELECT
FFF.CODPROD,
FFF.DESCRPROD,
FFF.QTD_CALC1 AS AMOSTRA_1,
FFF.QTD_CALC2 AS AMOSTRA_2,
FFF.QTD_CALC3 AS AMOSTRA_3,
FFF.MEDIA,
SQRT(((POWER((FFF.QTD_CALC1 - FFF.MEDIA),2))+(POWER((FFF.QTD_CALC2 - FFF.MEDIA),2))+(POWER((FFF.QTD_CALC3 - FFF.MEDIA),2))) / (3 -1)) AS DESV_PAD

FROM
(SELECT
DDD.CODPROD,
DDD.DESCRPROD,
(DDD.QTD_CALC1 + DDD.QTD_CALC2 + DDD.QTD_CALC3) / 3 AS MEDIA,
DDD.QTD_CALC1,
DDD.QTD_CALC2,
DDD.QTD_CALC3
FROM
(SELECT
PRO.CODPROD,
PRO.DESCRPROD,
((NVL(AAA.QTD,0) / 60) * 30) AS QTD_CALC1,
((NVL(BBB.QTD,0) / 60) * 30) AS QTD_CALC2,
((NVL(CCC.QTD,0) / 60) * 30) AS QTD_CALC3
FROM
TGFPRO PRO

LEFT JOIN (SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG) AS QTD,
DDD.ULT_DT,
CASE 
WHEN TO_DATE(DDD.ULT_DT) - TO_DATE(:ID_1) = 0 THEN 1
ELSE TO_DATE(DDD.ULT_DT) - TO_DATE(:ID_1) END AS VAR_TEMPO
FROM TGFCAB CAB,TGFPRO PRO, (SELECT
        ITE.CODPROD,
        MAX (CAB.DTNEG) AS ULT_DT
        FROM TGFITE ITE, TGFCAB CAB
        WHERE ITE.NUNOTA = CAB.NUNOTA
        AND CAB.DTNEG BETWEEN :ID_1 AND TO_DATE(:ID_1) + 60
        AND CAB.CODTIPOPER IN ('3200','3210','3262')
        AND CAB.CODEMP IN :P_EMP
        GROUP BY ITE.CODPROD) DDD,
TGFITE ITE
WHERE ITE.NUNOTA = CAB.NUNOTA
AND ITE.CODPROD = DDD.CODPROD
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN :ID_1 AND TO_DATE(:ID_1) + 60
AND CAB.CODTIPOPER IN ('3200','3210','3262')
AND CAB.CODEMP IN :P_EMP
GROUP BY ITE.CODPROD, PRO.DESCRPROD, DDD.ULT_DT) AAA ON PRO.CODPROD = AAA.CODPROD
LEFT JOIN (SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG) AS QTD,
DDD.ULT_DT,
CASE 
WHEN TO_DATE(DDD.ULT_DT) - TO_DATE(:ID_2) = 0 THEN 1
ELSE TO_DATE(DDD.ULT_DT) - TO_DATE(:ID_2) END AS VAR_TEMPO
FROM TGFCAB CAB,TGFPRO PRO, (SELECT
        ITE.CODPROD,
        MAX (CAB.DTNEG) AS ULT_DT
        FROM TGFITE ITE, TGFCAB CAB
        WHERE ITE.NUNOTA = CAB.NUNOTA
        AND CAB.DTNEG BETWEEN :ID_2 AND TO_DATE(:ID_2) + 60
        AND CAB.CODTIPOPER IN ('3200','3210','3262')
        AND CAB.CODEMP IN :P_EMP
        GROUP BY ITE.CODPROD) DDD,
TGFITE ITE
WHERE ITE.NUNOTA = CAB.NUNOTA
AND ITE.CODPROD = DDD.CODPROD
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN :ID_2 AND TO_DATE(:ID_2) + 60
AND CAB.CODTIPOPER IN ('3200','3210','3262')
AND CAB.CODEMP IN :P_EMP
GROUP BY ITE.CODPROD, PRO.DESCRPROD, DDD.ULT_DT) BBB ON PRO.CODPROD = BBB.CODPROD
LEFT JOIN (SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG) AS QTD,
DDD.ULT_DT,
CASE 
WHEN TO_DATE(DDD.ULT_DT) - TO_DATE(:ID_3) = 0 THEN 1
ELSE TO_DATE(DDD.ULT_DT) - TO_DATE(:ID_3) END AS VAR_TEMPO
FROM TGFCAB CAB,TGFPRO PRO, (SELECT
        ITE.CODPROD,
        MAX (CAB.DTNEG) AS ULT_DT
        FROM TGFITE ITE, TGFCAB CAB
        WHERE ITE.NUNOTA = CAB.NUNOTA
        AND CAB.DTNEG BETWEEN :ID_3 AND TO_DATE(:ID_3) + 60
        AND CAB.CODTIPOPER IN ('3200','3210','3262')
        AND CAB.CODEMP IN :P_EMP
        GROUP BY ITE.CODPROD) DDD,
TGFITE ITE
WHERE ITE.NUNOTA = CAB.NUNOTA
AND ITE.CODPROD = DDD.CODPROD
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN :ID_3 AND TO_DATE(:ID_3) + 60
AND CAB.CODTIPOPER IN ('3200','3210','3262')
AND CAB.CODEMP IN :P_EMP
GROUP BY ITE.CODPROD, PRO.DESCRPROD, DDD.ULT_DT) CCC ON PRO.CODPROD = CCC.CODPROD
WHERE
PRO.USOPROD = 'R' AND PRO.ATIVO = 'S' AND PRO.AD_COD_EX IS NULL) DDD) FFF) ANG