SELECT
FFF.ID,
FFF.IMPORTACAO,
FFF.INVOICE,
FFF.VALOR,
FFF.APROVACAO,
FFF.SITUACAO

FROM
(SELECT
FIP.IDFINIMP AS ID,
PRJ.IDENTIFICACAO AS IMPORTACAO,
INV.INVOICE,
CASE
WHEN FIP.VLR_USD IS NULL THEN 'R$ ' || FIP.VLRDESDOB
ELSE 'USD$ ' || FIP.VLR_USD END AS VALOR,
CASE 
WHEN FIP.APROVACAO = 'A' THEN 'GREEN'
WHEN FIP.APROVACAO = 'R' THEN 'RED'
WHEN FIP.APROVACAO = '' THEN 'YELLOW'
ELSE 'YELLOW' END AS APROVACAO,
CASE
WHEN FIP.TIPO IN ('I','P') AND FIP.IDFINIMP = AAA.AD_IDFINIMP AND FIP.VLRDESDOB = AAA.VLRDESDOB AND AAA.DHBAIXA IS NULL THEN 'LANÇADO'
WHEN FIP.TIPO IN ('I','P') AND FIP.IDFINIMP = AAA.AD_IDFINIMP AND FIP.VLRDESDOB = AAA.VLRDESDOB AND AAA.DHBAIXA IS NOT NULL THEN 'PAGO'
WHEN FIP.TIPO IN ('I','P') AND FIP.IDFINIMP = AAA.AD_IDFINIMP AND FIP.VLRDESDOB <> AAA.VLRDESDOB AND AAA.DHBAIXA IS NULL THEN 'LANÇADO DIVERGENTE'
WHEN FIP.TIPO IN ('I','P') AND FIP.IDFINIMP = AAA.AD_IDFINIMP AND FIP.VLRDESDOB <> AAA.VLRDESDOB AND AAA.DHBAIXA IS NOT NULL THEN 'PAGO DIVERGENTE'
ELSE ' ' END AS SITUACAO

FROM
AD_FINIMP FIP
LEFT JOIN TCSPRJ PRJ ON PRJ.CODPROJ = FIP.CODPROJ
LEFT JOIN AD_CADINV INV ON INV.IDINV = FIP.IDINVOICE
LEFT JOIN (SELECT 
    FIN.CODPROJ,
    FIN.CODPARC,S
    FIN.AD_IDFINIMP,
    FIN.VLRDESDOB,
    FIN.DHBAIXA
    FROM
    TGFFIN FIN) AAA ON FIP.CODPROJ = AAA.CODPROJ

WHERE
FIP.TIPO = 'P') FFF


WHERE
FFF.SITUACAO NOT IN ('PAGO') AND FFF.APROVACAO NOT IN ('GRREN')