SELECT
CAB.CODPARC,
PAR.RAZAOSOCIAL,
ITE.CODPROD,
PRO.DESCRPROD,
SUM(ITE.QTDNEG) AS QTD

FROM
TGFCAB CAB,
TGFPAR PAR,
TGFITE ITE,
TGFPRO PRO

WHERE
CAB.CODPARC = PAR.CODPARC
AND CAB.NUNOTA = ITE.NUNOTA
AND ITE.CODPROD = PRO.CODPROD
AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')
AND CAB.CODPARC = :CLIENTE
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN

GROUP BY
CAB.CODPARC,
PAR.RAZAOSOCIAL,
ITE.CODPROD,
PRO.DESCRPROD


ORDER BY
SUM(ITE.QTDNEG) DESC
