SELECT
IXN.CODEMP,
IXN.NUMNOTA,
IXN.CNPJPARC,
PAR.RAZAOSOCIAL,
IXN.DHEMISS,
IXN.DTVENC,
IXN.VLRNOTA,
CASE 
WHEN FIN.DHBAIXA IS NULL AND IXN.CNPJPARC IS NOT NULL THEN 'EM ABERTO' 
WHEN IXN.CNPJPARC IS NULL THEN 'Ñ CADASTRADO'
ELSE 'PAGO' END AS PAGO,
FIN.DHBAIXA,
CASE
WHEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') < TO_DATE(IXN.DTVENC, 'DD-MM-YYYY') AND FIN.DHBAIXA IS NULL THEN 'RED'
WHEN IXN.CNPJPARC IS NULL THEN 'GRAY'
WHEN FIN.DHBAIXA IS NOT NULL THEN 'GREEN'
ELSE 'YELLOW' END AS STATUS

FROM
TGFIXN IXN
LEFT JOIN TGFFIN FIN ON FIN.NUMNOTA = IXN.NUMNOTA AND FIN.CODTIPOPER IN ('4103','4102')
LEFT JOIN TGFPAR PAR ON IXN.CODPARC = PAR.CODPARC

WHERE
IXN.DHEMISS BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND IXN.TIPOCTE IN ('1','0')