SELECT
CAB.NUMNOTA,
CAB.DTNEG,
DECODE(CAB.CODTIPOPER,'3203','REMESSA EM GARANTIA','3260','REMESSA EM DEMONSTRAÇÃO','3209','REMESSA EM DEMONSTRAÇÃO','3202','REMESSA P/ CONSERTO','2109','ENTRADA P/ CONSERTO','2108','ENTRADA P/ CONSERTO','2119','ENTRADA P/ GARANTIA','2117','ENTRADA P/ GARANTIA') AS OPERACAO,
ITE.CODPROD,
PRO.DESCRPROD,
DECODE(ITE.PENDENTE,'N','NÃO','S','SIM') AS PENDENTE,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
CAB.NUNOTA,
TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') AS DIAS,
CASE 
WHEN ITE.PENDENTE = 'N' THEN 'BLUE'
WHEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') > '30' AND CAB.CODTIPOPER IN ('3203','2119','2117') AND ITE.PENDENTE = 'S' THEN 'RED'
WHEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') > '60' AND CAB.CODTIPOPER IN ('3260','3209') AND ITE.PENDENTE = 'S' THEN 'RED'
WHEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') > '180' AND CAB.CODTIPOPER IN ('3202','2109','2108') AND ITE.PENDENTE = 'S' THEN 'RED'
ELSE 'GREEN' END AS ALERTA

FROM
TGFCAB CAB,
TGFITE ITE,
TGFPRO PRO,
TGFPAR PAR

WHERE
CAB.NUNOTA = ITE.NUNOTA
AND ITE.CODPROD = PRO.CODPROD
AND CAB.CODPARC = PAR.CODPARC
AND CAB.CODTIPOPER IN ('3203','3260','3209','3202','2109','2108','2119','2117')
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND ITE.PENDENTE IN :P_PENDENTE
