SELECT
ICM.IDALIQ AS ID_ALIQ,
UFO.DESCRICAO AS ORIGEM,
UFD.DESCRICAO AS DESTINO,
CASE
WHEN ICM.CODRESTRICAO2 IN ('-1','2') THEN NULL
ELSE ICM.CODRESTRICAO2
END AS NCM,
CASE 
WHEN ICM.TIPRESTRICAO = 'Q' AND ICM.CODRESTRICAO = '1' THEN 'CONSUMO'
WHEN ICM.TIPRESTRICAO = 'Q' AND ICM.CODRESTRICAO = '2' THEN 'REVENDA'
WHEN ICM.TIPRESTRICAO = 'N' THEN 'DIFAL'
END AS TIPO,
ICM.ALIQUOTA AS ALIQ_INTER,
CASE 
WHEN ICM.TIPRESTRICAO = 'Q' THEN ICM.ALIQSUBTRIB
WHEN ICM.TIPRESTRICAO = 'N' THEN ICM.ALIQINTDEST
ELSE 0 END AS ALIQ_INTERNA,
CASE 
WHEN ICM.TIPRESTRICAO = 'Q' THEN ICM.PERCSTFCPINT
WHEN ICM.TIPRESTRICAO = 'N' THEN ICM.PERCICMSFCP
ELSE 0 END AS FECP,
ICM.MARGLUCRO AS MVA,
CASE 
WHEN ICM.TIPRESTRICAO = 'Q' THEN ICM.TIPCALCSTESPEC
WHEN ICM.TIPRESTRICAO = 'N' THEN ICM.TIPCALCDIFAL
ELSE 0 END AS CALC,
ICM.AD_DT_ATU AS DATA_ATUAL,
CASE
WHEN  TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(ICM.AD_DT_ATU, 'DD-MM-YYYY') > 30 THEN 'RED'
WHEN  TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(ICM.AD_DT_ATU, 'DD-MM-YYYY') <= 30 THEN 'GREEN'
ELSE 'RED'
END AS ATT

FROM
TGFICM ICM 
JOIN TSIUFS UFO ON ICM.UFORIG = UFO.CODUF
JOIN TSIUFS UFD ON ICM.UFDEST = UFD.CODUF

WHERE
ICM.TIPRESTRICAO IN ('Q','N') 
AND ICM.UFORIG IN ('1','2') 
AND ICM.CODRESTRICAO NOT IN ('4','3','5')

ORDER BY
ICM.AD_DT_ATU ASC,
UFO.DESCRICAO DESC,
UFD.DESCRICAO ASC,
TIPO ASC