SELECT
FIN.NUFIN,
FIN.NUMNOTA,
FIN.CODEMP,
FIN.CODPARC,
PAR.RAZAOSOCIAL,
FIN.VLRDESDOB,
FIN.DTVENC,
FIN.DHBAIXA,
FIN.PROVISAO,
CASE
WHEN FIN.DHBAIXA IS NULL AND CURRENT_DATE > FIN.DTVENC AND FIN.PROVISAO = 'N' THEN 'RED'
WHEN FIN.DHBAIXA IS NULL AND CURRENT_DATE <= FIN.DTVENC AND FIN.PROVISAO = 'N' THEN 'YELLOW'
WHEN FIN.DHBAIXA IS NOT NULL AND FIN.PROVISAO = 'N' THEN 'GREEN'
WHEN FIN.DHBAIXA IS NULL AND FIN.PROVISAO = 'S' THEN 'BLUE'
ELSE 'GRAY' END AS STATUS


FROM
TGFFIN FIN,
TGFPAR PAR

WHERE
FIN.CODPARC = PAR.CODPARC
AND PAR.CLIENTE = 'N'
AND FIN.DTVENC BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND FIN.RECDESP = '-1'
AND FIN.CODEMP IN :P_EMP
AND FIN.PROVISAO IN :P_PROV

ORDER BY
FIN.PROVISAO,
FIN.DTVENC