SELECT
ITC.CODPROD AS COD, 
PRO.DESCRPROD AS PRODUTO,
CAB.NUNOTA AS REQUISICAO, 
COT.NUMCOTACAO AS COTACAO, 
CAB.DTNEG AS DT_REQUISICAO, 
TRUNC(CAB.AD_PRAZO) AS DT_NECESSIDADE, 
TRUNC(COT.AD_PRZ_ENTRG) AS DT_ENTREGA,
PRO.LEADTIME AS LEAD_TIME,
CASE 
WHEN ITC.STATUSPRODCOT IN ('F') THEN 'GREEN'
WHEN ITC.STATUSPRODCOT IN ('A','E','O','P') THEN 'RED'
WHEN ITC.STATUSPRODCOT = 'C' THEN 'ORANGE' END AS SITUACAO,
CASE 
WHEN COT.SITUACAO = 'C' THEN 'CANCELADO'
WHEN (PRO.LEADTIME - 1) = (CASE WHEN COT.AD_PRZ_ENTRG IS NULL THEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') ELSE TO_DATE(COT.AD_PRZ_ENTRG, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') END) 
OR PRO.LEADTIME = (CASE WHEN COT.AD_PRZ_ENTRG IS NULL THEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') ELSE TO_DATE(COT.AD_PRZ_ENTRG, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') END) THEN 'Entrg na Data'
WHEN (PRO.LEADTIME - 1) > (CASE WHEN COT.AD_PRZ_ENTRG IS NULL THEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') ELSE TO_DATE(COT.AD_PRZ_ENTRG, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') END) THEN 'Entrg Antecipado'
WHEN PRO.LEADTIME < (CASE WHEN COT.AD_PRZ_ENTRG IS NULL THEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') ELSE TO_DATE(COT.AD_PRZ_ENTRG, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') END) THEN 'Entrg em Atraso'
ELSE 'Sem Leadtime'
END AS ENTREGA,
CASE WHEN COT.AD_PRZ_ENTRG IS NULL THEN TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') ELSE TO_DATE(COT.AD_PRZ_ENTRG, 'DD-MM-YYYY') - TO_DATE(CAB.DTNEG, 'DD-MM-YYYY') END AS VARIACAO_TEMPO,
CAB.DTNEG + PRO.LEADTIME AS DT_CALC_ENTREGA

FROM
TGFCOT COT,
TGFPRO PRO,
TGFCAB CAB,
TGFITC ITC

WHERE
COT.NUMCOTACAO = ITC.NUMCOTACAO 
AND ITC.CODPROD = PRO.CODPROD
AND COT.NUMCOTACAO = CAB.NUMCOTACAO
AND CAB.CODTIPOPER = '1006'
AND CAB.DTNEG >= '01/07/2021'
AND CAB.DTMOV >= :PERIODO.INI
AND CAB.DTMOV <= :PERIODO.FIN
AND COT.SITUACAO IN :P_STATUS