SELECT
COUNT (CAB.NUNOTA) AS QUANTIDADE,
DECODE (CAB.AD_ORIG_CTT,'1','CONTATO ATIVO','2','RECORRENTE','3','STATUS WHATSAPP','7','SITE / GOOGLE','4','FACEBOOK','5','INSTAGRAM','6','LINKEDIN','8','VISITA EXT','9','INDICAÇÃO','10','EVENTO','11','RADIO','12','REVISTA','0','OUTROS') AS ORIGEM

FROM 
TGFCAB CAB

WHERE
CAB.AD_ATENDENTE IS NOT NULL
AND CAB.CODTIPOPER IN ('3100','3103','3108','3109')
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN

GROUP BY
CAB.AD_ORIG_CTT