SELECT
ITE.CODPROD,
PRO.DESCRPROD,
ITE.CONTROLE,
SUM (ITE.QTDNEG) AS QTD,
CCC.CUSREP,
(SUM (ITE.QTDNEG) * CCC.CUSREP) AS CUSTO_TOTAL,
FFF.VLRNOTA

FROM
TGFITE ITE,
TGFCAB CAB,
TGFPRO PRO,
(SELECT 
                DDD.CONTROLE,
                DDD.CODPROD,
                CUS.CUSREP
                FROM TGFCUS CUS,
                    (SELECT 
                    MAX (EEE.DTATUAL) AS DATA,
                    EEE.CONTROLE,
                    EEE.CODPROD
                    FROM TGFCUS EEE
                    GROUP BY
                    EEE.CONTROLE,
                    EEE.CODPROD
                    ) DDD
                WHERE
                DDD.CONTROLE = CUS.CONTROLE
                AND DDD.CODPROD = CUS.CODPROD
                AND DDD.DATA = CUS.DTATUAL
) CCC,
(SELECT
        SUM(CAB.VLRNOTA) AS VLRNOTA
        FROM TGFCAB CAB
        WHERE
        CAB.CODTIPOPER IN ('3200','3205','3250','3262')
        AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
) FFF


WHERE
ITE.NUNOTA = CAB.NUNOTA
AND PRO.CODPROD = ITE.CODPROD
AND ITE.CODPROD = CCC.CODPROD AND ITE.CONTROLE = CCC.CONTROLE
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')

GROUP BY
ITE.CODPROD,
ITE.CONTROLE,
CCC.CUSREP,
FFF.VLRNOTA