SELECT
FIN.NUFIN,
FIN.CODEMP,
FIN.CODPARC,
PAR.RAZAOSOCIAL,
FIN.VLRDESDOB,
CASE WHEN FIN.AD_TIPO_INV = '1' THEN FIN.AD_VLR_USD
WHEN FIN.AD_TIPO_INV = '2' THEN FIN.AD_VLR_SERV
END AS VLR_USD,
FIN.CODPROJ,
PRJ.IDENTIFICACAO,
CASE WHEN FIN.AD_TIPO_INV = '1' THEN INV.INVOICE
WHEN FIN.AD_TIPO_INV = '2' THEN III.INVOICE
END AS INVOICE,
FIN.DTVENC,
CASE WHEN TO_CHAR(FIN.DTVENC, 'dd-mm-yyyy') >= TO_CHAR(CURRENT_DATE, 'dd-mm-yyyy') THEN 'YELLOW'
WHEN TO_CHAR(FIN.DTVENC, 'dd-mm-yyyy') < TO_CHAR(CURRENT_DATE, 'dd-mm-yyyy') AND FIN.DHBAIXA IS NULL THEN 'RED'
ELSE 'GREEN' END AS STATUS


FROM
TGFFIN FIN
LEFT JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
LEFT JOIN TCSPRJ PRJ ON FIN.CODPROJ = PRJ.CODPROJ
LEFT JOIN AD_CTRINV INV ON FIN.AD_INVOICE_ID = INV.IDINVOICE
LEFT JOIN AD_CTRINV III ON FIN.AD_INVOICE_ID = III.IDINVOICE

WHERE
FIN.AD_PROVIMPORT = 'S'