SELECT
OKK.CODPARC,
OKK.RAZAOSOCIAL,
ACA.SIT AS ACAO,
VLA.VLRACAO,
PPP.SIT AS PROT,
VLP.VLRPROT


FROM
TGFPAR OKK

FULL OUTER JOIN (SELECT
AAA.CODPARC,
COUNT (AAA.SITUACAO) AS SIT
FROM
(SELECT
FIN.CODPARC,
CASE
WHEN FIN.AD_TIT_ACJ = 'S' THEN 'A'
WHEN FIN.AD_TIT_PROT = 'S' THEN 'P'
WHEN FIN.AD_TIT_PROT IS NULL OR FIN.AD_TIT_PROT = 'N' AND FIN.AD_TIT_ACJ = 'N' OR FIN.AD_TIT_ACJ IS NULL THEN 'K' END AS SITUACAO
FROM
TGFFIN FIN) AAA
WHERE
AAA.SITUACAO = 'A'
GROUP BY
AAA.CODPARC) ACA ON OKK.CODPARC = ACA.CODPARC

FULL OUTER JOIN (SELECT
AAA.CODPARC,
COUNT (AAA.SITUACAO) AS SIT
FROM
(SELECT
FIN.CODPARC,
CASE
WHEN FIN.AD_TIT_ACJ = 'S' THEN 'A'
WHEN FIN.AD_TIT_PROT = 'S' THEN 'P'
WHEN FIN.AD_TIT_PROT IS NULL OR FIN.AD_TIT_PROT = 'N' AND FIN.AD_TIT_ACJ = 'N' OR FIN.AD_TIT_ACJ IS NULL THEN 'K' END AS SITUACAO
FROM
TGFFIN FIN) AAA
WHERE
AAA.SITUACAO = 'P'
GROUP BY
AAA.CODPARC) PPP ON OKK.CODPARC = PPP.CODPARC

FULL OUTER JOIN  (SELECT
FIN.CODPARC,
SUM (FIN.VLRDESDOB) AS VLRPROT
FROM
TGFFIN FIN
WHERE
FIN.AD_TIT_PROT = 'S'
GROUP BY 
FIN.CODPARC) VLP ON OKK.CODPARC = VLP.CODPARC

FULL OUTER JOIN  (SELECT
FIN.CODPARC,
SUM (FIN.VLRDESDOB) AS VLRACAO
FROM
TGFFIN FIN
WHERE
FIN.AD_TIT_ACJ = 'S'
GROUP BY 
FIN.CODPARC) VLA ON OKK.CODPARC = VLA.CODPARC

WHERE
OKK.CLIENTE = 'S'
AND ACA.SIT > '0'
OR PPP.SIT > '0'