-- VALOR DO FINANCEIRO
SELECT 
SUM(FIN.AD_VLR_USD) AS VLR_FIN,
FIN.CODPROJ,
FIN.CODPARC
FROM TGFFIN FIN
LEFT JOIN TCSPRJ PRJ ON FIN.CODPROJ = PRJ.CODPROJ
WHERE 
FIN.CODPROJ IS NOT NULL AND FIN.DHBAIXA IS NOT NULL AND FIN.CODPROJ <> 0 AND FIN.AD_VLR_USD IS NOT NULL
GROUP BY 
FIN.CODPROJ,
FIN.CODPARC



-- VALOR DAS INVOICES
SELECT 
CAB.CODPARC,
CAB.CODPROJ,
SUM(CAB.VLRTOTLIQITEMMOE) AS VLR_INVOICE
FROM TGFCAB CAB
LEFT JOIN TCSPRJ PRJ ON CAB.CODPROJ = PRJ.CODPROJ
WHERE CAB.CODPROJ IS NOT NULL AND CAB.CODPROJ <> 0 AND CAB.CODTIPOPER = '2000'
GROUP BY
CAB.CODPARC,
CAB.CODPROJ



-- VALOR DO IMPOSTOS
SELECT
AAA.CODPROJ,
AAA.AD_TIP_TRANSP,
CASE
WHEN AAA.AD_TIP_TRANSP = 'M' THEN AAA.VLR_INVOICE * 0.663
WHEN AAA.AD_TIP_TRANSP = 'A' THEN AAA.VLR_INVOICE * 0.951
WHEN AAA.AD_TIP_TRANSP = 'S' THEN AAA.VLR_INVOICE * 0.176
END AS VLR_IMP
FROM
(SELECT CAB.CODPARC,
CAB.CODPROJ,
PRJ.AD_TIP_TRANSP,
SUM(CAB.VLRTOTLIQITEMMOE) AS VLR_INVOICE
FROM TGFCAB CAB
LEFT JOIN TCSPRJ PRJ ON CAB.CODPROJ = PRJ.CODPROJ
WHERE CAB.CODPROJ IS NOT NULL AND CAB.CODPROJ <> 0 AND CAB.CODTIPOPER = '2000'
GROUP BY
CAB.CODPARC, CAB.CODPROJ, AD_TIP_TRANSP) AAA