SELECT
CLI.CODPARC,
CLI.RAZAOSOCIAL,
CLI.CLIENTE

FROM
(SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL,
CASE
WHEN AAA.VENDA IS NOT NULL THEN 'A'
WHEN BBB.VENDA IS NOT NULL THEN 'B'
ELSE 'C' END AS CLIENTE

FROM
TGFPAR PAR

LEFT JOIN(SELECT
    VEN.CODPARC,
    COUNT(VEN.NUNOTA) AS VENDA
    FROM
    TGFCAB VEN
    WHERE
    VEN.CODTIPOPER IN ('3200','3205','3250','3220')
    AND VEN.DTNEG BETWEEN (CURRENT_DATE - 365) AND CURRENT_DATE
    GROUP BY
    VEN.CODPARC) AAA ON PAR.CODPARC = AAA.CODPARC

LEFT JOIN(SELECT
    VEN.CODPARC,
    COUNT(VEN.NUNOTA) AS VENDA
    FROM
    TGFCAB VEN
    WHERE
    VEN.CODTIPOPER IN ('3200','3205','3250','3220')
    AND VEN.DTNEG BETWEEN '01/09/2019' AND (CURRENT_DATE - 366)
    GROUP BY
    VEN.CODPARC) BBB ON PAR.CODPARC = BBB.CODPARC

WHERE
PAR.CLIENTE = 'S'
AND PAR.ATIVO = 'S'
AND PAR.USUARIO = 'N'
AND PAR.CODPARC <> '0') CLI

WHERE
CLI.CLIENTE <> 'C'