SELECT
EMP.CODEMP,
REC.RECEBIMENTO,
CASE
WHEN EMP.CODEMP = '1' THEN :SALDO1
WHEN EMP.CODEMP = '2' THEN :SALDO2
WHEN EMP.CODEMP = '3' THEN :SALDO3
END AS SALDO,
FIX.FIXO,
VRV.VARIAV,
CASE
WHEN EMP.CODEMP = '1' THEN :FOLHA1
WHEN EMP.CODEMP = '2' THEN :FOLHA2
WHEN EMP.CODEMP = '3' THEN :FOLHA3
END AS FOLHA,
CASE
WHEN EMP.CODEMP = '1' THEN :IMPOSTO1
WHEN EMP.CODEMP = '2' THEN :IMPOSTO2
WHEN EMP.CODEMP = '3' THEN :IMPOSTO3
END AS IMPOSTO,
(REC.RECEBIMENTO * 0.056) AS MED_INAD,
CASE
WHEN EMP.CODEMP = '1' THEN REC.RECEBIMENTO + :SALDO1 - FIX.FIXO - VRV.VARIAV - :FOLHA1 - :IMPOSTO1 - (REC.RECEBIMENTO * 0.056)
WHEN EMP.CODEMP = '2' THEN REC.RECEBIMENTO + :SALDO2 - FIX.FIXO - VRV.VARIAV - :FOLHA2 - :IMPOSTO2 - (REC.RECEBIMENTO * 0.056)
WHEN EMP.CODEMP = '3' THEN REC.RECEBIMENTO + :SALDO3 - FIX.FIXO - VRV.VARIAV - :FOLHA3 - :IMPOSTO3 - (REC.RECEBIMENTO * 0.056)
END AS RESULTADO


FROM
TSIEMP EMP
LEFT JOIN (SELECT
SUM(FIN.VLRDESDOB) AS RECEBIMENTO,
FIN.CODEMP
FROM TGFFIN FIN
WHERE
FIN.RECDESP = '1'
AND FIN.PROVISAO = 'N'
AND FIN.DTVENC BETWEEN :PERIODO.INI AND :PERIODO.FIN
GROUP BY FIN.CODEMP) REC ON EMP.CODEMP = REC.CODEMP

LEFT JOIN (SELECT
SUM(FIN.VLRDESDOB) AS FIXO,
FIN.CODEMP
FROM TGFFIN FIN
WHERE
FIN.RECDESP = '-1'
AND FIN.PROVISAO = 'S'
AND FIN.AD_CUSTO_FIXO = 'S'
AND FIN.DTVENC BETWEEN :PERIODO.INI AND :PERIODO.FIN
GROUP BY FIN.CODEMP) FIX ON EMP.CODEMP = FIX.CODEMP

LEFT JOIN (SELECT
SUM(FIN.VLRDESDOB) AS VARIAV,
FIN.CODEMP
FROM TGFFIN FIN
WHERE
FIN.RECDESP = '-1'
AND FIN.PROVISAO = 'N'
AND FIN.DTVENC BETWEEN :PERIODO.INI AND :PERIODO.FIN
GROUP BY FIN.CODEMP) VRV ON EMP.CODEMP = VRV.CODEMP


WHERE
EMP.CODEMP IN :EMP
