/* query para consulta de notas de emprestimo de equipamentos para teste, CONTROLE DE DEMONSTRAÇÃO */

SELECT 
    CAB.CODPARC, 
    PAR.RAZAOSOCIAL, 
    CAB.NUMNOTA, 
    CAB.CODEMP, 
    CAB.AD_PREV_RETRN, 
    CAB.DTNEG 
CASE 
    WHEN CAB.AD_PREV_RETRN > TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') THEN 'RED'
    ELSE 'GREEN' END AS STATUS
FROM 
    TGFCAB CAB 
LEFT JOIN 
    TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
    CAB.CODTIPOPER = '3260' AND CAB.PENDENTE = 'S'
ORDER BY 
    CAB.DTNEG ASC 