SELECT
FIN.NUFIN,
FIN.NUMNOTA,
FIN.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL,
FIN.VLRDESDOB,
FIN.VLRBAIXA,
FIN.HISTORICO,
FIN.DHBAIXA,
DECODE(FIN.RECDESP,'1','RECEITA','-1','DESPESA') AS TIPO,
FIN.RECDESP,
FIN.DTNEG,
BCO.NOMEBCO,
DECODE(FIN.CODEMP,'1','KLG COMERCIO SJC','2','KLG INDUSTRIA','3','KLG COMERCIO MG') AS EMPRESA

FROM
TGFFIN FIN,
TGFPAR PAR,
TSIBCO BCO,
TSICTA CTA

WHERE
PAR.CODPARC = FIN.CODPARC
AND CTA.CODCTABCOINT = FIN.CODCTABCOINT
AND BCO.CODBCO = CTA.CODBCO
AND FIN.DHBAIXA IS NOT NULL
AND FIN.PROVISAO = 'N'

AND FIN.CODCTABCOINT = :CONTA
AND FIN.CODEMP = :EMPRESA
AND FIN.DHBAIXA BETWEEN :PERIODO.INI AND :PERIODO.FIN