SELECT
FIN.NUMNOTA,
TIT.DESCRTIPTIT,
FIN.CODPARC,
PAR.RAZAOSOCIAL,
ROUND(CURRENT_DATE - FIN.DTVENC) AS CONT,
FIN.VLRDESDOB,
FIN.DTVENC,
CASE 
WHEN FIN.AD_TIT_PROT = 'S' THEN 'GREEN'
WHEN (CURRENT_DATE - FIN.DTVENC) >= 10 AND (CURRENT_DATE - FIN.DTVENC) < 15 THEN 'YELLOW'
WHEN (CURRENT_DATE - FIN.DTVENC) >= 15 THEN 'RED'
ELSE 'GRAY' END AS PROTESTO,
CASE 
WHEN FIN.AD_TIT_ACJ = 'S' THEN 'GREEN'
WHEN (CURRENT_DATE - FIN.DTVENC) >= 30 AND (CURRENT_DATE - FIN.DTVENC) < 35 THEN 'YELLOW'
WHEN (CURRENT_DATE - FIN.DTVENC) >= 35 THEN 'RED'
ELSE 'GRAY' END AS ACAO_JUD

FROM
TGFFIN FIN,
TGFPAR PAR,
TGFTIT TIT

WHERE
FIN.DTVENC < CURRENT_DATE
AND FIN.DHBAIXA IS NULL
AND FIN.RECDESP = '1'
AND FIN.CODPARC = PAR.CODPARC
AND FIN.CODTIPTIT = TIT.CODTIPTIT