SELECT
    FIN.CODVEND,
    VEN.APELIDO,

    -- FATURAMENTO OFMETA
    SUM(FIN.OFM_BRUTO) AS OFM_BRUTO,
    SUM(FIN.OFM_LIQUIDO) AS OFM_LIQUIDO,

    -- FATURAMENTO ONMETA
    SUM(FIN.ONM_BRUTO) AS ONM_BRUTO,
    SUM(FIN.ONM_LIQUIDO) AS ONM_LIQUIDO,

    -- DEVOLUÇÕES OFMETA
    SUM(FIN.OFM_DEV_BRUTO) AS OFM_DEV_BRUTO,
    SUM(FIN.OFM_DEV_LIQUIDO) AS OFM_DEV_LIQUIDO,

    -- DEVOLUÇÕES ONMETA
    SUM(FIN.ONM_DEV_BRUTO) AS ONM_DEV_BRUTO,
    SUM(FIN.ONM_DEV_LIQUIDO) AS ONM_DEV_LIQUIDO

FROM
(
    SELECT
        CAB.CODVEND,
        CAB.NUNOTA,

        NVL(OFM.TOTAL_BRUTO,0)      AS OFM_BRUTO,
        NVL(OFM.TOTAL_LIQUIDO,0)    AS OFM_LIQUIDO,
        NVL(ONM.TOTAL_BRUTO,0)      AS ONM_BRUTO,
        NVL(ONM.TOTAL_LIQUIDO,0)    AS ONM_LIQUIDO,

        NVL(OFM_DEV.TOTAL_BRUTO,0)  AS OFM_DEV_BRUTO,
        NVL(OFM_DEV.TOTAL_LIQUIDO,0)AS OFM_DEV_LIQUIDO,
        NVL(ONM_DEV.TOTAL_BRUTO,0)  AS ONM_DEV_BRUTO,
        NVL(ONM_DEV.TOTAL_LIQUIDO,0)AS ONM_DEV_LIQUIDO

    FROM TGFCAB CAB

    -- FATURAMENTO OFFMETA
    LEFT JOIN
    (SELECT
        AAA.NUNOTA,
        SUM(AAA.TOTAL_BRUTO) AS TOTAL_BRUTO,
        SUM(AAA.TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
     FROM
        (SELECT
            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))
            + (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE)
            AS TOTAL_BRUTO,

            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) - NVL(DIF.VLR_DIFAL,0)
            AS TOTAL_LIQUIDO,

            CAB.NUNOTA

        FROM TGFITE ITE
        LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VLRDIFALDEST + VLRFCP) AS VLR_DIFAL
                   FROM TGFDIN DIN GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) DIF
                   ON DIF.NUNOTA = ITE.NUNOTA AND DIF.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR + VLRFCPINT) AS VLR_ST
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '2'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) SBT
                   ON SBT.NUNOTA = ITE.NUNOTA AND SBT.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR) AS VLR_IPI
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '3'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) IPI
                   ON IPI.NUNOTA = ITE.NUNOTA AND IPI.SEQUENCIA = ITE.SEQUENCIA

        WHERE
            CAB.CODTIPOPER IN ('3200','3205','3262','3220')
            AND ITE.CODPROD IN ('3335','3337','3988','10435','14445','15887','16136','16137','16098','15892','3189','3004','4053','4341','16135')
        ) AAA
     GROUP BY AAA.NUNOTA) OFM ON OFM.NUNOTA = CAB.NUNOTA


    -- FATURAMENTO ONMETA
    LEFT JOIN
    (SELECT
        AAA.NUNOTA,
        SUM(AAA.TOTAL_BRUTO) AS TOTAL_BRUTO,
        SUM(AAA.TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
     FROM
        (SELECT
            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))
            + (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE)
            AS TOTAL_BRUTO,

            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) - NVL(DIF.VLR_DIFAL,0)
            AS TOTAL_LIQUIDO,

            CAB.NUNOTA

        FROM TGFITE ITE
        LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VLRDIFALDEST + VLRFCP) AS VLR_DIFAL
                   FROM TGFDIN DIN GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) DIF
                   ON DIF.NUNOTA = ITE.NUNOTA AND DIF.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR + VLRFCPINT) AS VLR_ST
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '2'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) SBT
                   ON SBT.NUNOTA = ITE.NUNOTA AND SBT.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR) AS VLR_IPI
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '3'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) IPI
                   ON IPI.NUNOTA = ITE.NUNOTA AND IPI.SEQUENCIA = ITE.SEQUENCIA

        WHERE
            CAB.CODTIPOPER IN ('3200','3205','3262','3220')
            AND ITE.CODPROD NOT IN ('3335','3337','3988','10435','14445','15887','16136','16137','16098','15892','3189','3004','4053','4341','16135')
        ) AAA
     GROUP BY AAA.NUNOTA) ONM ON ONM.NUNOTA = CAB.NUNOTA


    -- DEVOLUÇÕES OFFMETA
    LEFT JOIN
    (SELECT
        AAA.NUNOTA,
        SUM(AAA.TOTAL_BRUTO) AS TOTAL_BRUTO,
        SUM(AAA.TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
     FROM
        (SELECT
            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) AS PROD,
            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))
            + (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE)
            AS TOTAL_BRUTO,

            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) - NVL(DIF.VLR_DIFAL,0)
            AS TOTAL_LIQUIDO,

            CAB.NUNOTA

        FROM TGFITE ITE
        LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VLRDIFALDEST + VLRFCP) AS VLR_DIFAL
                   FROM TGFDIN DIN GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) DIF
                   ON DIF.NUNOTA = ITE.NUNOTA AND DIF.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR + VLRFCPINT) AS VLR_ST
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '2'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) SBT
                   ON SBT.NUNOTA = ITE.NUNOTA AND SBT.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR) AS VLR_IPI
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '3'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) IPI
                   ON IPI.NUNOTA = ITE.NUNOTA AND IPI.SEQUENCIA = ITE.SEQUENCIA

        WHERE
            CAB.CODTIPOPER IN ('2200','2201','2208','2207')
            AND ITE.CODPROD IN ('3335','3337','3988','10435','14445','15887','16136','16137','16098','15892','3189','3004','4053','4341','16135')
        ) AAA
     GROUP BY AAA.NUNOTA) OFM_DEV ON OFM_DEV.NUNOTA = CAB.NUNOTA


    -- DEVOLUÇÕES ONMETA
    LEFT JOIN
    (SELECT
        AAA.NUNOTA,
        SUM(AAA.TOTAL_BRUTO) AS TOTAL_BRUTO,
        SUM(AAA.TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
     FROM
        (SELECT
            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) AS PROD,
            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))
            + (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE)
            AS TOTAL_BRUTO,

            ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) - NVL(DIF.VLR_DIFAL,0)
            AS TOTAL_LIQUIDO,

            CAB.NUNOTA

        FROM TGFITE ITE
        LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VLRDIFALDEST + VLRFCP) AS VLR_DIFAL
                   FROM TGFDIN DIN GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) DIF
                   ON DIF.NUNOTA = ITE.NUNOTA AND DIF.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR + VLRFCPINT) AS VLR_ST
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '2'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) SBT
                   ON SBT.NUNOTA = ITE.NUNOTA AND SBT.SEQUENCIA = ITE.SEQUENCIA

        LEFT JOIN (SELECT DIN.NUNOTA,DIN.SEQUENCIA,SUM(DIN.VALOR) AS VLR_IPI
                   FROM TGFDIN DIN WHERE DIN.CODIMP = '3'
                   GROUP BY DIN.NUNOTA,DIN.SEQUENCIA) IPI
                   ON IPI.NUNOTA = ITE.NUNOTA AND IPI.SEQUENCIA = ITE.SEQUENCIA

        WHERE
            CAB.CODTIPOPER IN ('2200','2201','2208','2207')
            AND ITE.CODPROD NOT IN ('3335','3337','3988','10435','14445','15887','16136','16137','16098','15892','3189','3004','4053','4341','16135')
        ) AAA
     GROUP BY AAA.NUNOTA) ONM_DEV ON ONM_DEV.NUNOTA = CAB.NUNOTA


    WHERE CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN

) FIN

LEFT JOIN TGFVEN VEN ON VEN.CODVEND = FIN.CODVEND

WHERE VEN.AD_VENDAS_ATIVO = 'S'

GROUP BY FIN.CODVEND, VEN.APELIDO
