<gadget>
  <level id="lvl_aqenl0u" description="Principal">
    <container orientacao="V" tamanhoRelativo="100">
      <grid id="grd_aqenl0y" useNewGrid="S">
        <expression type="sql" data-source="MGEDS"><![CDATA[SELECT
ZZZ.MES,
ZZZ.DIAMES,
ZZZ.SALDO_FIN,
ZZZ.SALDO_BANCO,
ZZZ.RECEBIMENTO,
ZZZ.PREVFAT,
ZZZ.FOLHA,
ZZZ.IMPOSTOS,
ZZZ.FIXO,
ZZZ.VARIAV,
ZZZ.VLRIMPORT,
ZZZ.IMPIMPORT,
ZZZ.VLRPROD,
ZZZ.OUTROS,
CASE 
WHEN ZZZ.MES = TO_CHAR(CURRENT_DATE, 'mm-yyyy') THEN ZZZ.SALDO_FIN + (ZZZ.PREVFAT * 0.195)      
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)   
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)     
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)       
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)      
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)      
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)       
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)      
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 8, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)      
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 9, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 8, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)     
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 10, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 9, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 8, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)      
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 11, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 10, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 9, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 8, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)    
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 12, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 11, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 10, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 9, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 8, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)  
WHEN ZZZ.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy') THEN ZZZ.SALDO_FIN + (LAG(ZZZ.PREVFAT, 13, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 12, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 11, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 10, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 9, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 8, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 7, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 6, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 5, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 4, 0) OVER (ORDER BY ZZZ.DIAMES) * 1) + (LAG(ZZZ.PREVFAT, 3, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.995) + (LAG(ZZZ.PREVFAT, 2, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.72) + (LAG(ZZZ.PREVFAT, 1, 0) OVER (ORDER BY ZZZ.DIAMES) * 0.53) + (ZZZ.PREVFAT * 0.195)
END AS SALDO

FROM
    (SELECT
    CASE 
    WHEN SSS.MES = TO_CHAR(CURRENT_DATE, 'mm-yyyy') THEN SSS.RESULT
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 8, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 9, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 8, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 10, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 9, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 8, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 11, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 10, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 9, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 8, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 12, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 11, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 10, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 9, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 8, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    WHEN SSS.MES = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy') THEN SSS.RESULT+(LAG(SSS.RESULT, 13, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 12, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 11, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 10, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 9, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 8, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 7, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 6, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 5, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 4, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 3, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 2, 0) OVER (ORDER BY SSS.DIAMES))+(LAG(SSS.RESULT, 1, 0) OVER (ORDER BY SSS.DIAMES))
    END AS SALDO_FIN,
    SSS.SALDO AS SALDO_BANCO,
    SSS.MES,
    SSS.DIAMES,
    SSS.RECEBIMENTO,
    SSS.PREVFAT,
    SSS.FOLHA,
    SSS.IMPOSTOS,
    SSS.FIXO,
    SSS.VARIAV,
    SSS.OUTROS,
    SSS.VLRIMPORT,
    SSS.IMPIMPORT,
    SSS.VLRPROD
    FROM
        (SELECT
        NVL(AAA.SALDO, 0) + NVL(AAA.RECEBIMENTO, 0) - NVL(AAA.FIXO, 0) - NVL(AAA.VARIAV, 0) - NVL(AAA.OUTROS, 0) - NVL(AAA.VLRIMPORT, 0) - NVL(AAA.IMPIMPORT, 0) - NVL(AAA.VLRPROD, 0) - NVL(AAA.IMPOSTOS, 0) - NVL(AAA.FOLHA, 0) AS RESULT,
        NVL(AAA.SALDO, 0) AS SALDO,
        AAA.MES,
        AAA.DIAMES,
        NVL(AAA.RECEBIMENTO, 0) AS RECEBIMENTO,
        NVL(AAA.PREVFAT, 0) AS PREVFAT,
        NVL(AAA.FOLHA, 0) AS FOLHA,
        NVL(AAA.IMPOSTOS, 0) AS IMPOSTOS,
        NVL(AAA.FIXO, 0) AS FIXO,
        NVL(AAA.VARIAV, 0) AS VARIAV,
        NVL(AAA.OUTROS, 0) AS OUTROS,
        NVL(AAA.VLRIMPORT, 0) AS VLRIMPORT,
        NVL(AAA.IMPIMPORT, 0) AS IMPIMPORT,
        NVL(AAA.VLRPROD, 0 ) AS VLRPROD
        FROM

            (SELECT
            SAL.SALDO,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT AS IMPIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
                (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')
                -- REMOVER ESTE FILTRO DE GNRE QAUNDO FOR CONSERTADO
                AND FIN.CODTIPTIT <> '47'
                OR FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'N'
                AND FIN.AD_PROVIMPORT = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')
                -- REMOVER ESTE FILTRO DE GNRE QAUNDO FOR CONSERTADO
                AND FIN.CODTIPTIT <> '47') VRV,
            /*SALDO BANCARIO*/
            (SELECT
                SUM(SSS.SALDO) AS SALDO
                FROM
                    (SELECT
                        SBC.CODCTABCOINT,
                        SBC.SALDOREAL + NVL(MBC.MOV,0) AS SALDO,
                        TO_CHAR(SBC.REFERENCIA, 'mm-yyyy') AS REFERENCIA
                        FROM TGFSBC SBC
                        LEFT JOIN (SELECT
                            MBC.CODCTABCOINT,  
                            SUM (MBC.VLRLANC * MBC.RECDESP) AS MOV
                            FROM
                            TGFMBC MBC
                            WHERE
                            TO_CHAR(DTLANC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')
                            GROUP BY
                            MBC.CODCTABCOINT) MBC ON MBC.CODCTABCOINT = SBC.CODCTABCOINT
                            WHERE TO_CHAR(SBC.REFERENCIA, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')
                            AND SBC.CODCTABCOINT <> '21') SSS) SAL,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(CURRENT_DATE, 'mm-yyyy')) IPT
            UNION 

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 1), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 2), 'mm-yyyy')) IPT
            UNION
            
            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 3), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 4), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 5), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 6), 'mm-yyyy')) IPT
UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 7), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 8), 'mm-yyyy')) IPT
UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 9), 'mm-yyyy')) IPT
UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 10), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 11), 'mm-yyyy')) IPT
            UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 12), 'mm-yyyy')) IPT
UNION

            SELECT
            0,
            NVL(REC.RECEBIMENTO, 0) AS RECEBIMENTO,
            PFC.PREVFAT,
            PFC.FOLHA,
            PFC.IMPOSTOS,
            FIX.FIXO,
            VRV.VARIAV,
            PFC.OUTROS,
            IPC.VLRIMPORT,
            IPT.VLRIMPORT,
            PFC.VLRPROD,
            TO_CHAR(PFC.DIAMES, 'mm-yyyy') AS MES,
            PFC.DIAMES
            FROM
            /*RECEBIMENTOS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS RECEBIMENTO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '1'
                AND FIN.PROVISAO = 'N'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')
                AND FIN.DHBAIXA IS NULL) REC,
            /*CONTAS FIXAS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS FIXO
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO = 'S'
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')) FIX,
            /*CONTAS VARIAVEIS*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VARIAV
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1'
                AND FIN.DHBAIXA IS NULL
                AND FIN.AD_CUSTO_FIXO IS NULL
                AND FIN.AD_PROVIMPORT IS NULL
                AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')) VRV,
            /*VALORES DE PREVISÕES DO FLUXO DE CAIXA*/
            (SELECT
                SUM(SALDOREAL) AS SALDO,
                TO_CHAR(REFERENCIA, 'mm-yyyy') AS REFERENCIA
                FROM TGFSBC 
                WHERE TO_CHAR(REFERENCIA, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')
                GROUP BY REFERENCIA) SAL,
                (SELECT
                (FLX.FOLHA1 + FLX.FOLHA2 + FLX.FOLHA3 + FLX.FOLHA4) AS FOLHA,
                (FLX.IMP1 + FLX.IMP2 + FLX.IMP3 + FLX.IMP4) AS IMPOSTOS,
                FLX.PREVFAT,
                FLX.OUTROS,        
                FLX.VLRPROD,
                FLX.DIAMES
                FROM AD_FLXCAX FLX
                WHERE TO_CHAR(FLX.DIAMES, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')) PFC,
            /*VALOR DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'N' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy') OR
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP IS NULL AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')) IPC,
            /*IMPOSTOS DA IMPORTAÇÃO*/
            (SELECT
                SUM(FIN.VLRDESDOB) AS VLRIMPORT
                FROM TGFFIN FIN
                WHERE
                FIN.RECDESP = '-1' AND FIN.DHBAIXA IS NULL AND FIN.AD_PROVIMPORT = 'S' AND FIN.AD_TXIMP = 'S' AND TO_CHAR(FIN.DTVENC, 'mm-yyyy') = TO_CHAR(ADD_MONTHS(CURRENT_DATE, 13), 'mm-yyyy')) IPT

            ) AAA
            ORDER BY
            MES) SSS) ZZZ

ORDER BY
ZZZ.DIAMES
]]></expression>
        <metadata>
          <field name="MES" label="MES" type="S" visible="true" useFooter="false"/>
          <field name="DIAMES" label="DIAMES" type="D" visible="true" useFooter="false"/>
          <field name="SALDO_FIN" label="SALDO_FIN" type="F" visible="false" useFooter="false"/>
          <field name="SALDO_BANCO" label="SALDO BANCO" type="F" visible="true" useFooter="false"/>
          <field name="RECEBIMENTO" label="RECEBIMENTO" type="F" visible="true" useFooter="false"/>
          <field name="PREVFAT" label="PREV FAT" type="F" visible="true" useFooter="false"/>
          <field name="FOLHA" label="FOLHA" type="F" visible="true" useFooter="false"/>
          <field name="IMPOSTOS" label="IMPOSTOS" type="F" visible="true" useFooter="false"/>
          <field name="FIXO" label="FIXO" type="F" visible="true" useFooter="false"/>
          <field name="VARIAV" label="VARIAVEL" type="F" visible="true" useFooter="false"/>
          <field name="VLRIMPORT" label="VLR IMPORT" type="F" visible="true" useFooter="false"/>
          <field name="IMPIMPORT" label="IMP IMPORT" type="F" visible="true" useFooter="false"/>
          <field name="VLRPROD" label="VLR PRODUÇ" type="F" visible="true" useFooter="false"/>
          <field name="OUTROS" label="VLR OUTROS" type="F" visible="true" useFooter="false"/>
          <field name="SALDO" label="SALDO" type="F" visible="true" useFooter="false"/>
        </metadata>
      </grid>
    </container>
  </level>
</gadget>