SELECT
ITE.CODPROD,
PRO.DESCRPROD,
III.QTD_IMP,
SUM (ITE.QTDNEG) AS QTD,
DDD.ULT_DT,
TO_DATE(DDD.ULT_DT, 'DD-MM-YYYY') - TO_DATE(:PERIODO.INI, 'DD-MM-YYYY') AS VARIACAO_TEMPO

FROM
TGFCAB CAB,
TGFPRO PRO, 
(SELECT
        ITE.CODPROD,
        MAX (CAB.DTNEG) AS ULT_DT

        FROM
        TGFITE ITE,
        TGFCAB CAB

        WHERE
        ITE.NUNOTA = CAB.NUNOTA
        AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
        AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')

        GROUP BY
        ITE.CODPROD
    ) DDD,
TGFITE ITE
LEFT JOIN (SELECT
        ITE.CODPROD,
        SUM (ITE.QTDNEG) AS QTD_IMP

        FROM
        TGFITE ITE,
        TGFCAB CAB

        WHERE
        ITE.NUNOTA = CAB.NUNOTA
        AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
        AND CAB.CODTIPOPER IN ('2106')

        GROUP BY
        ITE.CODPROD
    ) III ON ITE.CODPROD = III.CODPROD

WHERE
ITE.NUNOTA = CAB.NUNOTA
AND ITE.CODPROD = DDD.CODPROD
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')

GROUP BY
ITE.CODPROD,
III.QTD_IMP,
PRO.DESCRPROD,
DDD.ULT_DT
