SELECT
EST.CODPROD,
PRO.DESCRPROD,
LOC.DESCRLOCAL,
EST.ESTOQUE

FROM
TGFEST EST,
TGFPRO PRO,
TGFLOC LOC

WHERE
EST.CODPROD = PRO.CODPROD
AND EST.CODLOCAL = LOC.CODLOCAL
AND EST.CODLOCAL IN ('010520000','010370000')