SELECT
SUM(YYY.RESULTADO) AS MARGE_RES,
AVG(YYY.MC) AS MC,
SUM(YYY.VLRNOTA) AS FATUR,
YYY.CODVEND


FROM
(SELECT 
CASE 
WHEN XXX.VLRNOTA <> '0' THEN ((XXX.RESULTADO*100)/XXX.VLRNOTA) 
ELSE 0 END AS MC,
XXX.RESULTADO,
XXX.VLRNOTA,
XXX.CUSTO,
XXX.DTNEG,
XXX.CODVEND,
XXX.AD_DESP_AT,
XXX.VLRFRETE,
XXX.IMP_PEC,
XXX.IMP_SERV,
XXX.NUNOTA

FROM
(SELECT
NVL((AAA.VLRNOTA-AAA.AD_DESP_AT-AAA.VLRFRETE-AAA.IMP_SERV-AAA.IMP_PEC-AAA.VLRST-AAA.CUSTO),0) AS VLR_MARGEM,
NVL((AAA.VLRNOTA-AAA.AD_DESP_AT-AAA.VLRFRETE-AAA.IMP_SERV-AAA.IMP_PEC-AAA.VLRST-AAA.CUSTO),0) AS RESULTADO,
AAA.VLRNOTA,
AAA.CUSTO,
AAA.DTNEG,
AAA.CODVEND,
AAA.AD_DESP_AT,
AAA.VLRFRETE,
NVL(AAA.IMP_PEC,0) AS IMP_PEC,
AAA.IMP_SERV,
AAA.NUNOTA

FROM
(SELECT
NVL(CAB.AD_DESP_AT,0) AS AD_DESP_AT,
NVL(TTT.VLRNOTA,0) AS VLRNOTA,
NVL(CAB.VLRFRETE,0) AS VLRFRETE,
NVL(ISS.IMP_SERV,0) AS IMP_SERV,
NVL(IPP.IMP_PEC,0) AS IMP_PEC,
NVL(III.VLRIMP,0) AS VLRST,
NVL(CCC.CUSTO,0) AS CUSTO,
CAB.DTNEG,
CAB.CODVEND,
CAB.NUNOTA

FROM
TGFCAB CAB

/*Retorna Valor Total da OS faturada*/
LEFT JOIN(SELECT
    SUM(ITE.VLRTOT-ITE.VLRDESC+ITE.VLRIPI+ITE.VLRSUBST) AS VLRNOTA,
    CAB.VLRFRETE,
    CAB.VLRNOTA AS VLRTOT,
    CAB.NUNOTA
    FROM
    TGFITE ITE
    LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
    LEFT JOIN TGFVAR VAR1 ON ITE.NUNOTA = VAR1.NUNOTAORIG
    LEFT JOIN TGFVAR VAR2 ON VAR1.NUNOTA = VAR2.NUNOTAORIG
    WHERE
    CAB.CODTIPOPER = '1001'
    AND CAB.NUNOTA > '70000'
    AND VAR2.NUNOTA IS NOT NULL
    GROUP BY
    CAB.VLRFRETE,
    CAB.VLRNOTA,
    CAB.NUNOTA) TTT ON TTT.NUNOTA = CAB.NUNOTA

/*Retorna IMPOSTO SERVIÇO*/
LEFT JOIN(SELECT
    (SSS.VLRSERV * (SSS.ALIQ_SERV/100)) AS IMP_SERV,
    SSS.NUNOTA
    FROM 
    (SELECT
    SUM(ITE.VLRTOT) AS VLRSERV,
    ITE.NUNOTA,
    PSN.ALIQUOTA AS ALIQ_SERV
    FROM
    TGFITE ITE,
    TGFPRO PRO,
    TGFPSN PSN
    WHERE
    ITE.CODPROD = PRO.CODPROD
    AND PRO.USOPROD = 'S'
    AND PSN.NUPARTILHA = (SELECT
    MAX(PSN.NUPARTILHA)
    FROM
    TGFPSN PSN
    WHERE
    PSN.TIPOSN = '3')
    GROUP BY
    ITE.NUNOTA,
    PSN.ALIQUOTA) SSS) ISS ON CAB.NUNOTA = ISS.NUNOTA

/*Retorna IMPOSTO PEÇAS*/    
LEFT JOIN(SELECT
    (PPP.VLRPEC * (PPP.ALIQ_PEC/100)) AS IMP_PEC,
    PPP.NUNOTA
    FROM 
    (SELECT
    SUM(ITE.VLRTOT) AS VLRPEC,
        ITE.NUNOTA,
        PSN.ALIQUOTA AS ALIQ_PEC
    FROM
    TGFITE ITE,
    TGFPRO PRO,
    TGFPSN PSN
    WHERE
    ITE.CODPROD = PRO.CODPROD
    AND PRO.USOPROD <> 'S'
    AND PSN.NUPARTILHA = (SELECT
    MAX(PSN.NUPARTILHA)
    FROM
    TGFPSN PSN
    WHERE
    PSN.TIPOSN = '1')
    GROUP BY
    ITE.NUNOTA,
    PSN.ALIQUOTA) PPP) IPP ON CAB.NUNOTA = IPP.NUNOTA

/*Retorna ST*/
LEFT JOIN (SELECT
            DIN.NUNOTA,
            SUM(DIN.VALOR + DIN.VLRDIFALDEST + VLRFCP) AS VLRIMP
            FROM TGFDIN DIN
            WHERE
            DIN.CODIMP = '2'
            GROUP BY
            DIN.NUNOTA
            ) III ON CAB.NUNOTA = III.NUNOTA

/*Retorna o Custo vs Quantidade de Produtos*/
LEFT JOIN (SELECT
        CC3.NUNOTA,
        SUM(CC3.CALC) AS CUSTO
        FROM
        (SELECT
            ITE.NUNOTA,
            (CC2.CUSGER * ITE.QTDNEG) AS CALC
            FROM
            TGFITE ITE
            /*Retorna o Custo*/
            LEFT JOIN (SELECT 
                    DDD.CONTROLE,
                    DDD.CODPROD,
                    CUS.CUSGER
                    FROM TGFCUS CUS,
                        (SELECT 
                        MAX (EEE.DTATUAL) AS DATA,
                        EEE.CONTROLE,
                        EEE.CODPROD
                        FROM TGFCUS EEE
                        GROUP BY
                        EEE.CONTROLE,
                        EEE.CODPROD
                        ) DDD
                    WHERE
                    DDD.CONTROLE = CUS.CONTROLE
                    AND DDD.CODPROD = CUS.CODPROD
                    AND DDD.DATA = CUS.DTATUAL
                    )CC2 ON ITE.CODPROD = CC2.CODPROD AND ITE.CONTROLE = CC2.CONTROLE
        )CC3
    GROUP BY
    CC3.NUNOTA
    ) CCC ON CAB.NUNOTA = CCC.NUNOTA

WHERE
CAB.CODTIPOPER = '1001'
) AAA
WHERE
AAA.DTNEG BETWEEN '01/03/2022' AND '18/03/2022'
) XXX
WHERE
XXX.VLRNOTA <> 0
) YYY

GROUP BY
YYY.CODVEND
