SELECT
PAL.CODPROD AS COD_MATRIZ,
PRO.DESCRPROD AS DESCRICAO,
PAL.CODPRODALT AS COD_ALT,
ROUND(SUM(EST.ESTOQUE)) AS ESTQ_ALT

FROM 
TGFPAL PAL
LEFT JOIN TGFPRO PRO ON PAL.CODPROD = PRO.CODPROD
LEFT JOIN TGFEST EST ON PAL.CODPRODALT = EST.CODPROD

WHERE
PRO.USOPROD = 'M' AND PRO.AD_CODMATRIZ = 'S' AND PRO.CODPROD = :PROD

GROUP BY
PAL.CODPROD,
PRO.DESCRPROD,
PAL.CODPRODALT