SELECT
CAB.NUMNOTA,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
PAR.DTNEG,
ITE.CODPROD,
PRO.DESCRPROD,
ITE.QTDNEG,
CAB.CODVEND,
VEN.APELIDO


FROM
TGFITE ITE,
TGFCAB CAB,
TGFPRO PRO,
TGFPAR PAR,
TGFVEN VEN

WHERE
ITE.NUNOTA = CAB.NUNOTA
AND ITE.CODPROD = PRO.CODPROD
AND PRO.AD_VEND_SERV = 'S'
AND CAB.CODPARC = PAR.CODPARC
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CAB.CODTIPOPER IN (3200, 3205, 3250, 3262)
AND CAB.CODVEND = VEN.CODVEND

ORDER BY
PAR.DTNEG,
CAB.NUMNOTA