SELECT
COUNT (CAB.NUNOTA) AS QUANTIDADE,
DECODE (CAB.AD_CONCORRENTE,'1','ALFA','2','XCMG','3','TSUNO','4','ZOOMLION','5','IRMEN','6','PERNANBUCO','7','LOAD CONTROL','8','TECNIC','9','MESTIRA','O','OUTRO') AS CONCORRENTE

FROM
TGFCAB CAB

WHERE
CAB.CODTIPOPER IN ('3100','3103')
AND CAB.AD_PERD = 'S'
AND CAB.DTNEG >= :PERIODO.INI
AND CAB.DTNEG <= :PERIODO.FIN
AND CAB.CODVEND IN :P_VEND
AND CAB.AD_MOT_CANC = 'F'

GROUP BY
DECODE (CAB.AD_CONCORRENTE) AS CONCORRENTE