SELECT
COUNT (CAB.NUNOTA) AS QUANTIDADE,
DECODE (CAB.AD_MOT_CANC,'C','PAGAMENTO','D','PRAZO','E','EM FALTA','F','CONCORRENTE','N','NÃO ERA A PEÇA','p','PREÇO','R','RELACIONAMENTO','O','ORÇAMENTO DUPLICADO','M','PESQUISA DE MERCADO','V','REVENDA') AS MOTIVO

FROM
TGFCAB CAB

WHERE
CAB.CODTIPOPER IN ('3100','3103')
AND CAB.AD_PERD = 'S'
AND CAB.DTNEG >= :PERIODO.INI
AND CAB.DTNEG <= :PERIODO.FIN
AND CAB.CODVEND IN :P_VEND

GROUP BY
CAB.AD_MOT_CANC