SELECT
COUNT (CAB.NUNOTA) AS QUANTIDADE,
SUM (CAB.VLRNOTA) AS TOTAL

FROM
TGFCAB CAB

WHERE
CAB.CODTIPOPER IN ('3100','3103')
AND CAB.AD_PERD = 'S'
AND CAB.DTNEG >= :PERIODO.INI
AND CAB.DTNEG <= :PERIODO.FIN
AND CAB.CODVEND IN :P_VEND

GROUP BY
CAB.AD_MOT_CANC