SELECT
VVV.DTNEG,
DDD.VLR,
VVV.VENDA

FROM
(SELECT
    CAB.DTNEG,
    SUM(CAB.VLRNOTA) AS VENDA
    FROM 
    TGFCAB CAB
    WHERE
    CAB.DTNEG BETWEEN '01/07/2022' AND '31/07/2022'
    AND CAB.CODTIPOPER = '3250'
    GROUP BY
    CAB.DTNEG) VVV
FULL OUTER JOIN (SELECT
    SUM(FIN.VLRDESDOB) AS VLR,
    FIN.DHBAIXA
    FROM
    TGFFIN FIN
    WHERE
    FIN.DHBAIXA BETWEEN '01/07/2022' AND '31/07/2022'
    AND FIN.RECDESP = '-1'
    AND FIN.PROVISAO = 'N'
    AND FIN.CODCENCUS = '03080000'
    GROUP BY
    FIN.DHBAIXA) DDD ON VVV.DTNEG = DDD.DHBAIXA

