SELECT
PRO.CODPROD,
PRO.DESCRPROD,
AAA.QTD AS QTD_IMP1,
BBB.QTD AS QTD_IMP2,
CCC.QTD AS QTD_IMP3
FROM
TGFPRO PRO

LEFT JOIN (SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG) AS QTD
FROM TGFCAB CAB,TGFPRO PRO, TGFITE ITE
WHERE ITE.NUNOTA = CAB.NUNOTA
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN '19/10/2022' AND TO_DATE('19/10/2022') + 60
AND CAB.CODTIPOPER IN ('2106')
AND CAB.CODEMP IN ('1','2')
GROUP BY ITE.CODPROD, PRO.DESCRPROD) AAA ON PRO.CODPROD = AAA.CODPROD

LEFT JOIN (SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG) AS QTD
FROM TGFCAB CAB,TGFPRO PRO,TGFITE ITE
WHERE ITE.NUNOTA = CAB.NUNOTA
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN '09/08/2022' AND TO_DATE('09/08/2022') + 60
AND CAB.CODTIPOPER IN ('2106')
AND CAB.CODEMP IN ('1','2')
GROUP BY ITE.CODPROD, PRO.DESCRPROD) BBB ON PRO.CODPROD = BBB.CODPROD

LEFT JOIN (SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG) AS QTD
FROM TGFCAB CAB,TGFPRO PRO,TGFITE ITE
WHERE ITE.NUNOTA = CAB.NUNOTA
AND PRO.CODPROD = ITE.CODPROD
AND CAB.DTNEG BETWEEN '07/06/2022' AND TO_DATE('07/06/2022') + 60
AND CAB.CODTIPOPER IN ('2106')
AND CAB.CODEMP IN ('1','2')
GROUP BY ITE.CODPROD, PRO.DESCRPROD) CCC ON PRO.CODPROD = CCC.CODPROD


WHERE
PRO.USOPROD = 'R' AND PRO.ATIVO = 'S' AND PRO.AD_COD_EX IS NULL