SELECT
ITE.NUNOTA AS N_UNICO,
CAB.NUMNOTA AS NF,
CAB.CODPARC AS COD_CLIENTE,
PAR.RAZAOSOCIAL AS CLIENTE,
ITE.PENDENTE AS PENDENTE,
ITE.CODPROD AS COD_PROD,
PRO.DESCRPROD AS PRODUTO,
ITE.QTDNEG AS QUANT

FROM
TGFITE ITE,
TGFCAB CAB,
TGFPRO PRO,
TGFPAR PAR

WHERE
ITE.NUNOTA = CAB.NUNOTA
AND ITE.CODPROD = PRO.CODPROD
AND CAB.CODPARC = PAR.CODPARC
AND CAB.CODTIPOPER = '3260'
AND ITE.PENDENTE = 'S'
