SELECT
    AAA.CODVEND,
    AAA.APELIDO,
    AAA.VLRTOT,
    AAA.CUSTO,
    AAA.ICMS + AAA.PISCOFINS + AAA.COMISSAO AS GV,
    CASE WHEN (AAA.VLRTOT - AAA.CUSTO - (AAA.ICMS + AAA.PISCOFINS + AAA.COMISSAO) - (AAA.VLRTOT * 16 / 100) ) > 0 THEN 'BLUE' ELSE 'RED' END AS SEMAFORO_LUCRO
FROM (
        SELECT
            CAB.CODVEND,
            VEN.APELIDO,
            SUM((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * TPO.GOLDEV ) AS VLRTOT,
            SUM(CUS.CUSGER * ITE.QTDNEG * TPO.GOLDEV ) AS CUSTO,
            SUM(((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * ITE.ALIQICMS / 100) * TPO.GOLDEV) AS ICMS,
            SUM(((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * 9.25 / 100) * TPO.GOLDEV) AS PISCOFINS,
            SUM(((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * 1 / 100) * TPO.GOLDEV) AS COMISSAO
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFCUS CUS ON ITE.CODPROD = CUS.CODPROD AND ITE.CONTROLE = CUS.CONTROLE 
JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
JOIN TGFTOP TPO ON CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER
WHERE CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CAB.CODEMP IN :CODEMP
AND CAB.STATUSNOTA = 'L'
AND TPO.GOLSINAL = -1
AND CAB.CODTIPOPER IN (3200, 3205, 3250, 3262)
AND CUS.DTATUAL = (SELECT MAX(C.DTATUAL) FROM TGFCUS C WHERE CUS.CODPROD = C.CODPROD AND CUS.CONTROLE = C.CONTROLE AND C.DTATUAL <= CAB.DTNEG)
GROUP BY CAB.CODVEND, VEN.APELIDO
)AAA
ORDER BY 3