SELECT
SUM((SELECT CAB.VLRNOTA 
    FROM TGFCAB CAB
    WHERE
    CAB.CODTIPOPER IN ('3100','3103')
    AND CAB.DTNEG >= :PERIODO.INI
    AND CAB.DTNEG <= :PERIODO.FIN
    AND CAB.CODVEND IN :P_VEND
    AND CAB.PENDENTE = 'N'
    AND CAB.AD_N_NEG_VEND IS NULL)) AS COM NEGOCIAÇÃO,
SUM((SELECT CAB.VLRNOT 
    FROM TGFCAB CAB
    WHERE
    CAB.CODTIPOPER IN ('3100','3103')
    AND CAB.DTNEG >= :PERIODO.INI
    AND CAB.DTNEG <= :PERIODO.FIN
    AND CAB.CODVEND IN :P_VEND
    AND CAB.PENDENTE = 'N'
    AND CAB.AD_N_NEG_VEND IS NOT NULL)) AS SEM NEGOCIAÇÃO,
CAB.DTNEG

FROM TGFCAB CAB

WHERE
CAB.CODTIPOPER IN ('3100','3103')
AND CAB.DTNEG >= :PERIODO.INI
AND CAB.DTNEG <= :PERIODO.FIN
AND CAB.CODVEND IN :P_VEND
AND CAB.PENDENTE = 'N'

GROUP BY
CAB.DTNEG