SELECT
CAB.NUNOTA AS OS,
PAR.RAZAOSOCIAL,
CASE WHEN CAB.AD_STAT_OS IN ('0','2','6','5','4','3')  THEN 'EM ABERTO'
    WHEN CAB.AD_STAT_OS = '1' THEN 'FINALIZADO'
    ELSE '' END AS PENDENTE,
CAB.CODEMP,
CAB.AD_MAT_ENV_CONS AS MATERIAL,
CAB.DTMOV,
CASE WHEN CAB.AD_STAT_OS = 0 AND TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTMOV, 'DD-MM-YYYY') > '3' THEN 'RED'
    ELSE 'GREEN' END AS EMAVALIACAO,
CASE WHEN CAB.AD_STAT_OS = 2 AND TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - TO_DATE(CAB.DTMOV, 'DD-MM-YYYY') > '5' THEN 'RED'
    ELSE 'GREEN' END AS AGUARDAPROV,
CASE WHEN CAB.AD_STAT_OS IN ('5','4','3') AND TO_DATE(CURRENT_DATE, 'DD-MM-YYYY') - (TO_DATE(CAB.AD_DT_APROV, 'DD-MM-YYYY') + CAB.AD_PRAZ_MAT + CAB.AD_PRAZ_REP) < '0' THEN 'RED'
    ELSE 'GREEN' END AS APROVACAO,
    (TO_DATE(CAB.AD_DT_APROV, 'DD-MM-YYYY') + CAB.AD_PRAZ_MAT + CAB.AD_PRAZ_REP) AS DATA,
CASE WHEN AD_ADIA_CONC IS NOT NULL THEN TO_DATE(AD_ADIA_CONC, 'DD-MM-YYYY') ELSE (TO_DATE(CAB.AD_DT_APROV, 'DD-MM-YYYY') - 0)  END AS ADIADO

FROM
TGFCAB CAB,
TGFPAR PAR

WHERE
CAB.CODPARC = PAR.CODPARC
AND CAB.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CAB.CODTIPOPER = '1001'
AND CAB.AD_STAT_OS IN :P_STATUS
