SELECT
SUM(CAB.VLRNOTA) AS VLRTOTAL,
TO_CHAR(CAB.DTNEG, 'DD/MM/YYYY') AS DIA

FROM
TGFCAB CAB

WHERE
CAB.CODTIPOPER IN ('3101','3102','3104')
AND CAB.DTNEG >= :PERIODO.INI
AND CAB.DTNEG <= :PERIODO.FIN

GROUP BY 
TO_CHAR(CAB.DTNEG, 'DD/MM/YYYY')

ORDER BY
TO_CHAR(CAB.DTNEG, 'DD/MM/YYYY')