SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM(ITE.QTDNEG) AS QTD

FROM
TGFCAB CAB,
TGFITE ITE,
TGFPRO PRO

WHERE
CAB.NUNOTA = ITE.NUNOTA
AND ITE.CODPROD = PRO.CODPROD
AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN

GROUP BY
ITE.CODPROD,
PRO.DESCRPROD


ORDER BY
SUM(ITE.QTDNEG) DESC