SELECT
KKK.CODVEND, 
KKK.VENDEDOR,
KKK.AD_CLAS_VENDEDOR,
KKK.AD_UNIDADE,
KKK.META,
KKK.FATURAMENTO,
KKK.FAT_BRUTO,
KKK.MC, 
SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) AS FAT_LIQ_REAL,
CASE 
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '50000,00' AND SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) <= '99999,99' AND KKK.FATURAMENTO < KKK.META THEN '0.4'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '100000,00' AND SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) <= '149999,99' AND KKK.FATURAMENTO < KKK.META THEN '0.5'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '150000,00' AND SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) <= '199999,99' AND KKK.FATURAMENTO < KKK.META THEN '1.0'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '200000,00' AND KKK.FATURAMENTO < '1200000,00' THEN '1.5'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '50000,00' AND SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) <= '99999,99' AND KKK.FATURAMENTO > KKK.META THEN '0.36'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '100000,00' AND SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) <= '149999,99' AND KKK.FATURAMENTO > KKK.META THEN '0.7'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '150000,00' AND SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) <= '199999,99' AND KKK.FATURAMENTO > KKK.META THEN '1.2'
WHEN SUM(KKK.FAT_LIQ - NVL(KKK.DEVOL,0)) >= '200000,00' AND KKK.FATURAMENTO > '1200000,00' THEN '1.7'
ELSE '0' END AS COFIECIENTE,

CASE 
WHEN KKK.MC > '40' AND KKK.MC < '50' THEN '90'
WHEN KKK.MC >= '50' THEN '100'
ELSE '0' END AS COEF_PORCT

FROM
(SELECT
AAA.CODVEND, 
AAA.APELIDO AS VENDEDOR,
AAA.AD_CLAS_VENDEDOR,
AAA.AD_UNIDADE,
AAA.META,
AAA.FATURAMENTO,
AAA.DEVOL,
SUM(AAA.VLRNOTA - NVL(AAA.VLRFRETE,0) - NVL(AAA.VLRIPI,0) - NVL(AAA.VLRSUBST,0) - NVL(AAA.VLRICMSDIFALDEST,0) - NVL(AAA.VLRICMSFCP,0)) AS FAT_LIQ,
SUM(AAA.VLRNOTA) AS FAT_BRUTO,
AVG((AAA.VLRNOTA - AAA.VLRFRETE - AAA.CUSTO - AAA.VLRIMP) / AAA.VLRNOTA * 100.00) AS MC

FROM 
/*Criação de uma View para trazer os resultados ja pré-selecionados*/
    (SELECT
    CAB.NUNOTA,
    CAB.CODVEND,
    VEN.APELIDO,
    VEN.AD_VENDAS_ATIVO,
    VEN.AD_UNIDADE,
    VEN.AD_CLAS_VENDEDOR,
    MMM.META,
    CAB.VLRNOTA,
    ZZZ.DEVOL,
    CAB.VLRFRETE,
    III.VLRIMP,
    CAB.DTNEG,
    CAB.VLRIPI,
    CAB.VLRSUBST,
    CAB.VLRICMSDIFALDEST,
    CAB.VLRICMSFCP,
    FFF.FATURAMENTO,
    CCC.CUSTO

    FROM 
    TGFCAB CAB
    /*Retorna a Devolução*/
    LEFT JOIN (SELECT
        CAB.CODVEND,
        SUM(CAB.VLRNOTA) AS DEVOL
        FROM TGFCAB CAB
        WHERE
        CAB.CODTIPOPER IN ('2207','2208','2201','2200')
        AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
        AND CAB.CODVEND IN :P_CODVEND
        GROUP BY
        CAB.CODVEND
        ) ZZZ ON ZZZ.CODVEND = CAB.CODVEND
   
    /*Retorna a FATURAMENTO BRUTO INDIVIDUAL DO VENDEDOR*/
    LEFT JOIN (SELECT
        CAB.CODVEND,
        SUM(CAB.VLRNOTA) AS VLRNOTA
        FROM TGFCAB CAB
        WHERE
        CAB.CODTIPOPER IN ('3200','3205','3250','3262')
        AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
        AND CAB.CODVEND IN :P_CODVEND
        GROUP BY
        CAB.CODVEND
        ) FF2 ON FF2.CODVEND = CAB.CODVEND
    /*Retorna o Custo vs Quantidade de Produtos*/
    LEFT JOIN (SELECT
        CC3.NUNOTA,
        SUM(CC3.CALC) AS CUSTO
        FROM
        (SELECT
            ITE.NUNOTA,
            (CC2.CUSGER * ITE.QTDNEG) AS CALC
            FROM
            TGFITE ITE
            /*Retorna o Custo*/
            LEFT JOIN (SELECT 
                    DDD.CONTROLE,
                    DDD.CODPROD,
                    CUS.CUSGER
                    FROM TGFCUS CUS,
                        (SELECT 
                        MAX (EEE.DTATUAL) AS DATA,
                        EEE.CONTROLE,
                        EEE.CODPROD
                        FROM TGFCUS EEE
                        GROUP BY
                        EEE.CONTROLE,
                        EEE.CODPROD
                        ) DDD
                    WHERE
                    DDD.CONTROLE = CUS.CONTROLE
                    AND DDD.CODPROD = CUS.CODPROD
                    AND DDD.DATA = CUS.DTATUAL
                    )CC2 ON ITE.CODPROD = CC2.CODPROD AND ITE.CONTROLE = CC2.CONTROLE
        )CC3
    GROUP BY
    CC3.NUNOTA
    ) CCC ON CAB.NUNOTA = CCC.NUNOTA,
        TGFVEN VEN,
            /*Retorna os Impostos*/
            (SELECT
            DIN.NUNOTA,
            SUM(DIN.VALOR + DIN.VLRDIFALDEST + VLRFCP) AS VLRIMP
            FROM TGFDIN DIN
            GROUP BY
            DIN.NUNOTA
            ) III,
        /*Retorna o Faturamento Total*/
            (SELECT
            SUM(CAB.VLRNOTA) AS FATURAMENTO
            FROM TGFCAB CAB
            WHERE
            CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
            AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')
            AND CAB.CODVEND IN :P_CODVEND
            ) FFF,
            /*Retorna a Meta Total*/
            (SELECT
            SUM (MM2.META) AS META
            FROM
            (SELECT
            CASE 
            WHEN VEN.AD_CLAS_VENDEDOR = 'A' THEN '200000'
            WHEN VEN.AD_CLAS_VENDEDOR = 'B' THEN '150000'
            WHEN VEN.AD_CLAS_VENDEDOR = 'C' THEN '100000'
            ELSE '0' END AS META
            FROM
            TGFVEN VEN 
            WHERE
            VEN.AD_VENDAS_ATIVO = 'S') MM2
            ) MMM


     WHERE
    CAB.NUNOTA = III.NUNOTA
    AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')
    AND CAB.CODVEND = VEN.CODVEND
    AND VEN.AD_VENDAS_ATIVO IS NOT NULL
    AND CAB.CODVEND IN :P_CODVEND

) AAA

WHERE
AAA.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN

GROUP BY
AAA.CODVEND, 
AAA.APELIDO,
AAA.AD_CLAS_VENDEDOR,
AAA.META,
AAA.AD_UNIDADE,
AAA.FATURAMENTO,
AAA.DEVOL
) KKK
GROUP BY
KKK.CODVEND, 
KKK.VENDEDOR,
KKK.AD_CLAS_VENDEDOR,
KKK.AD_UNIDADE,
KKK.META,
KKK.FATURAMENTO,
KKK.FAT_BRUTO,
KKK.MC