SELECT
SUM (CAB.VLRNOTA - CAB.VLRIPI - CAB.VLRSUBST - CAB.VLRFRETE - CAB.VLRICMSDIFALDEST - CAB.VLRICMSFCP) AS VLR_LIQUIDO

FROM
TGFCAB CAB,
TGFVEN VEN

WHERE
CAB.CODVEND = VEN.CODVEND
AND CAB.DTNEG >= :PERIODO.INI
AND CAB.DTNEG <= :PERIODO.FIN
AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')


