WITH VENDAS AS (
    SELECT
        UNI.CORG AS COD_MATRIZ,
        TRUNC(CAB.DTNEG, 'MM') AS MES_REFERENCIA,
        TO_CHAR(CAB.DTNEG, 'MM/YYYY') AS MES_ANO,
        SUM(ITE.QTDNEG) AS QTD_TOTAL_VENDIDA
    FROM
        TGFITE ITE
        JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
        /* Mapeamento de produto → matriz */
        LEFT JOIN (
            SELECT
                PRO.CODPROD AS CORG,
                PAL.CODPRODALT AS CALT
            FROM TGFPRO PRO
            LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
            WHERE PRO.USOPROD = 'R'
              AND PRO.AD_COD_EX IS NULL
              AND PRO.AD_TIP_ALT = 'M'
              AND PAL.CODPRODALT IS NOT NULL
            UNION ALL
            SELECT
                PRO.CODPROD AS CORG,
                PRO.CODPROD AS CALT
            FROM TGFPRO PRO
            WHERE PRO.USOPROD = 'R'
              AND PRO.AD_COD_EX IS NULL
              AND PRO.AD_TIP_ALT = 'M'
        ) UNI ON UNI.CALT = ITE.CODPROD
    WHERE
        CAB.CODTIPOPER IN ('3200','3205','3220')
        AND CAB.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), -36) -- últimos 3 anos
    GROUP BY
        UNI.CORG,
        TRUNC(CAB.DTNEG, 'MM'),
        TO_CHAR(CAB.DTNEG, 'MM/YYYY')
),
RANKED AS (
    SELECT
        V.*,
        ROW_NUMBER() OVER (
            PARTITION BY V.COD_MATRIZ
            ORDER BY V.QTD_TOTAL_VENDIDA DESC
        ) AS RNK
    FROM VENDAS V
)
SELECT
    COD_MATRIZ AS CODIGO,
    MAX(CASE WHEN RNK = 1 THEN QTD_TOTAL_VENDIDA END) AS PICO_1,
    MAX(CASE WHEN RNK = 2 THEN QTD_TOTAL_VENDIDA END) AS PICO_2,
    MAX(CASE WHEN RNK = 3 THEN QTD_TOTAL_VENDIDA END) AS PICO_3,
    MAX(CASE WHEN RNK = 4 THEN QTD_TOTAL_VENDIDA END) AS PICO_4,
    MAX(CASE WHEN RNK = 5 THEN QTD_TOTAL_VENDIDA END) AS PICO_5,
    MAX(CASE WHEN RNK = 6 THEN QTD_TOTAL_VENDIDA END) AS PICO_6,
    MAX(CASE WHEN RNK = 1 THEN MES_ANO END) AS PERIODO_1,
    MAX(CASE WHEN RNK = 2 THEN MES_ANO END) AS PERIODO_2,
    MAX(CASE WHEN RNK = 3 THEN MES_ANO END) AS PERIODO_3,
    MAX(CASE WHEN RNK = 4 THEN MES_ANO END) AS PERIODO_4,
    MAX(CASE WHEN RNK = 5 THEN MES_ANO END) AS PERIODO_5,
    MAX(CASE WHEN RNK = 6 THEN MES_ANO END) AS PERIODO_6
FROM
    RANKED
WHERE
    RNK <= 6
GROUP BY
    COD_MATRIZ
ORDER BY
    COD_MATRIZ