SELECT
DISTINCT(PRO.NCM) AS NCM,
PRO.CODIPI,
IPI.PERCENTUAL

FROM
TGFPRO PRO
LEFT JOIN TGFIPI IPI ON PRO.CODIPI = IPI.CODIPI

WHERE
PRO.USOPROD IN ('R','V','2')



UPDATE TGFPRO set CODIPI = 'X' where NCM = 'X'