SELECT
CAB.NUNOTA,
CAB.NUMNOTA,
CAB.AD_UF,
CAB.DTNEG,
ITE.CODPROD,
ITE.SEQUENCIA,
ITE.ORIGPROD,
ITE.CODBENEFNAUF

FROM
TGFCAB CAB
LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA

WHERE
CAB.CODEMP = '5'
AND CAB.DTNEG >= '17/08/2025'
AND CAB.CODTIPOPER IN ('3200','3205','3210')
AND ITE.ORIGPROD = 1