-- CLIENTES COM COMPRA NOS ULTIMOS 60 DIAS
SELECT
AAA.CODPARC,
AAA.CLIENTE,
--AAA.CONTATO,
--AAA.TELEFONE || ' - ' || AAA.CELULAR AS TELEFONE,
AAA.EMAIL,
AAA.ULT_VENDA
FROM
(SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL AS CLIENTE,
CTT.NOMECONTATO AS CONTATO,
CTT.TELEFONE,
CTT.EMAIL,
CTT.CELULAR,
VVV.ULT_VENDA
FROM
TGFPAR PAR
LEFT JOIN TGFCTT CTT ON CTT.CODPARC = PAR.CODPARC
LEFT JOIN (SELECT MAX(CAB.DTNEG)  AS ULT_VENDA, CAB.CODPARC
FROM TGFCAB CAB
WHERE CAB.CODTIPOPER IN (3200, 3205, 3250, 3262) GROUP BY CAB.CODPARC) VVV ON VVV.CODPARC = PAR.CODPARC
WHERE
PAR.ATIVO = 'S'
AND PAR.CLIENTE = 'S'
AND CTT.ATIVO = 'S') AAA
WHERE
AAA.ULT_VENDA > TO_DATE(CURRENT_DATE) - 60


-- 6 MESES SEM COMPRA
SELECT
AAA.CODPARC,
AAA.CLIENTE,
AAA.CONTATO,
AAA.TELEFONE || ' - ' || AAA.CELULAR AS TELEFONE,
AAA.EMAIL,
AAA.ULT_VENDA
FROM
(SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL AS CLIENTE,
CTT.NOMECONTATO AS CONTATO,
CTT.TELEFONE,
CTT.EMAIL,
CTT.CELULAR,
VVV.ULT_VENDA
FROM
TGFPAR PAR
LEFT JOIN TGFCTT CTT ON CTT.CODPARC = PAR.CODPARC
LEFT JOIN (SELECT MAX(CAB.DTNEG)  AS ULT_VENDA, CAB.CODPARC
FROM TGFCAB CAB
WHERE CAB.CODTIPOPER IN (3200, 3205, 3250, 3262) GROUP BY CAB.CODPARC) VVV ON VVV.CODPARC = PAR.CODPARC
WHERE
PAR.ATIVO = 'S'
AND PAR.CLIENTE = 'S'
AND CTT.ATIVO = 'S') AAA
WHERE
AAA.ULT_VENDA < TO_DATE(CURRENT_DATE) - 180


-- 1 ANO SEM COMPRA
SELECT
AAA.CODPARC,
AAA.CLIENTE,
AAA.CONTATO,
AAA.TELEFONE || ' - ' || AAA.CELULAR AS TELEFONE,
AAA.EMAIL,
AAA.ULT_VENDA
FROM
(SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL AS CLIENTE,
CTT.NOMECONTATO AS CONTATO,
CTT.TELEFONE,
CTT.EMAIL,
CTT.CELULAR,
VVV.ULT_VENDA
FROM
TGFPAR PAR
LEFT JOIN TGFCTT CTT ON CTT.CODPARC = PAR.CODPARC
LEFT JOIN (SELECT MAX(CAB.DTNEG)  AS ULT_VENDA, CAB.CODPARC
FROM TGFCAB CAB
WHERE CAB.CODTIPOPER IN (3200, 3205, 3250, 3262) GROUP BY CAB.CODPARC) VVV ON VVV.CODPARC = PAR.CODPARC
WHERE
PAR.ATIVO = 'S'
AND PAR.CLIENTE = 'S'
AND CTT.ATIVO = 'S') AAA
WHERE
AAA.ULT_VENDA < TO_DATE(CURRENT_DATE) - 365


-- NUNCA COMPROU OU COMPROU A MAIS DE 4 ANOS
SELECT
AAA.CODPARC,
AAA.CLIENTE,
AAA.CONTATO,
AAA.TELEFONE || ' - ' || AAA.CELULAR AS TELEFONE,
AAA.EMAIL,
AAA.ULT_VENDA
FROM
(SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL AS CLIENTE,
CTT.NOMECONTATO AS CONTATO,
CTT.TELEFONE,
CTT.EMAIL,
CTT.CELULAR,
VVV.ULT_VENDA
FROM
TGFPAR PAR
LEFT JOIN TGFCTT CTT ON CTT.CODPARC = PAR.CODPARC
LEFT JOIN (SELECT MAX(CAB.DTNEG)  AS ULT_VENDA, CAB.CODPARC
FROM TGFCAB CAB
WHERE CAB.CODTIPOPER IN (3200, 3205, 3250, 3262) GROUP BY CAB.CODPARC) VVV ON VVV.CODPARC = PAR.CODPARC
WHERE
PAR.ATIVO = 'S'
AND PAR.CLIENTE = 'S'
AND CTT.ATIVO = 'S') AAA
WHERE
AAA.ULT_VENDA IS NULL

