SELECT
VLV.CODPROD,
VLV.DESCRPROD,
VLV.AD_TIP_ALT,
VLV.VLR_UNIT_LIQ,
PAL.CODPROD AS CODMAT
FROM
(SELECT
ITE.CODPROD,
PRO.DESCRPROD,
PRO.AD_TIP_ALT,
ITE.VLRUNIT + (ITE.VLRIPI / ITE.QTDNEG) AS VLR_UNIT_LIQ,
ITE.NUNOTA
FROM
TGFITE ITE
LEFT JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE
CAB.CODTIPOPER IN ('2106')
AND CAB.DTNEG > '28/02/2023') VLV
LEFT JOIN TGFPAL PAL ON PAL.CODPRODALT = VLV.CODPROD

