SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL,
PAR.EMAIL,
CTT.EMAIL,
DAT.DATA

FROM
(SELECT
CAB.CODPARC,
MAX(CAB.DTNEG) AS DATA
FROM
TGFCAB CAB
WHERE
CAB.CODTIPOPER IN ('3200','3205','3250')
GROUP BY
CAB.CODPARC) DAT
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = DAT.CODPARC
LEFT JOIN TGFCTT CTT ON CTT.CODPARC = DAT.CODPARC

WHERE
DAT.DATA < (CURRENT_DATE - 365)