SELECT 
PRO.CODPROD,
PRO.DESCRPROD AS DESCRICAO,
(NVL(ALT.EST_ALT,0)+NVL(MAT.EST_MAT,0)) AS ESTOQUE

FROM
TGFPRO PRO
LEFT JOIN (SELECT
PRO.CODPROD,
PRO.DESCRPROD AS DESCRICAO,
SUM(EST.ESTOQUE) AS EST_ALT
FROM
TGFPRO PRO
LEFT JOIN TGFPAL PAL ON PRO.CODPROD = PAL.CODPROD
LEFT JOIN TGFEST EST ON PAL.CODPRODALT = EST.CODPROD
WHERE
EST.ESTOQUE > '0' 
AND PRO.USOPROD IN ('M')
AND EST.CODLOCAL = '010390000'
AND PRO.AD_CODMATRIZ = 'S'
GROUP BY
PRO.CODPROD,
PRO.DESCRPROD) ALT ON PRO.CODPROD = ALT.CODPROD
LEFT JOIN (SELECT
EST.CODPROD,
PRO.DESCRPROD AS DESCRICAO,
SUM(EST.ESTOQUE) AS EST_MAT
FROM 
TGFEST EST
JOIN TGFPRO PRO ON EST.CODPROD = PRO.CODPROD
JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL
WHERE
EST.ESTOQUE > '0' 
AND PRO.USOPROD IN ('M')
AND EST.CODLOCAL = '010390000'
GROUP BY
EST.CODPROD,
PRO.DESCRPROD) MAT ON PRO.CODPROD = MAT.CODPROD

WHERE
PRO.USOPROD IN ('M')