SELECT
FIN.CODVEND,
VEN.APELIDO,
SUM(FIN.OFM_BRUTO) AS OFM_BRUTO,
SUM(FIN.OFM_LIQUIDO) AS OFM_LIQUIDO,
SUM(FIN.ONM_BRUTO) AS ONM_BRUTO,
SUM(FIN.ONM_LIQUIDO) AS ONM_LIQUIDO

FROM
(SELECT
CAB.CODVEND,
CAB.NUNOTA,
NVL(OFM.TOTAL_BRUTO,0) AS OFM_BRUTO,
NVL(OFM.TOTAL_LIQUIDO,0) AS OFM_LIQUIDO,
NVL(ONM.TOTAL_BRUTO,0) AS ONM_BRUTO,
NVL(ONM.TOTAL_LIQUIDO,0) AS ONM_LIQUIDO,
CAB.VLRNOTA

FROM
TGFCAB CAB
-- FATURAMENTO OFF META
LEFT JOIN (SELECT
AAA.NUNOTA,
SUM(AAA.TOTAL_BRUTO) AS TOTAL_BRUTO,
SUM(AAA.TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
FROM
(SELECT
    (ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC AS PROD,
    NVL(SBT.VLR_ST,0) AS VLR_ST,
    NVL(IPI.VLR_IPI,0) AS VLR_IPI,
    NVL(DIF.VLR_DIFAL,0) AS VLR_DIFAL,
    (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE) AS VLR_FRETE_ITE,
    ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0)) + (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE) AS TOTAL_BRUTO,
    ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) - NVL(DIF.VLR_DIFAL,0) AS TOTAL_LIQUIDO,
    CAB.NUNOTA
    FROM
    TGFITE ITE
    LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
    -- VLR DO DIFAL DO PRODUTO
    LEFT JOIN (SELECT
                DIN.NUNOTA,
                DIN.SEQUENCIA,
                SUM(DIN.VLRDIFALDEST + VLRFCP) AS VLR_DIFAL
                FROM TGFDIN DIN
                GROUP BY
                DIN.NUNOTA,
                DIN.SEQUENCIA
                ) DIF ON DIF.NUNOTA = ITE.NUNOTA AND DIF.SEQUENCIA = ITE.SEQUENCIA
    -- VLR DO ST DO PRODUTO
    LEFT JOIN (SELECT
                DIN.NUNOTA,
                DIN.SEQUENCIA,
                SUM(DIN.VALOR + VLRFCPINT) AS VLR_ST
                FROM TGFDIN DIN
                WHERE DIN.CODIMP = '2'
                GROUP BY
                DIN.NUNOTA,
                DIN.SEQUENCIA
                ) SBT ON SBT.NUNOTA = ITE.NUNOTA AND SBT.SEQUENCIA = ITE.SEQUENCIA
    -- VLR DO IPI DO PRODUTO
    LEFT JOIN (SELECT
                DIN.NUNOTA,
                DIN.SEQUENCIA,
                SUM(DIN.VALOR) AS VLR_IPI
                FROM TGFDIN DIN
                WHERE DIN.CODIMP = '3'
                GROUP BY
                DIN.NUNOTA,
                DIN.SEQUENCIA
                ) IPI ON IPI.NUNOTA = ITE.NUNOTA AND IPI.SEQUENCIA = ITE.SEQUENCIA
    WHERE
    CAB.CODTIPOPER IN ('3200','3205','3262','3220')
    AND ITE.CODPROD IN ('3335','3337','3988','10435','14445','15887','16136','16137','16098','15892','3189','3004','4053','4341','16135')
) AAA
GROUP BY 
AAA.NUNOTA) OFM ON CAB.NUNOTA = OFM.NUNOTA
-- FATURAMENTO ON META
LEFT JOIN (SELECT
    AAA.NUNOTA,
    SUM(AAA.TOTAL_BRUTO) AS TOTAL_BRUTO,
    SUM(AAA.TOTAL_LIQUIDO) AS TOTAL_LIQUIDO
    FROM
    (SELECT
        (ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC AS PROD,
        NVL(SBT.VLR_ST,0) AS VLR_ST,
        NVL(IPI.VLR_IPI,0) AS VLR_IPI,
        NVL(DIF.VLR_DIFAL,0) AS VLR_DIFAL,
        (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE) AS VLR_FRETE_ITE,
        ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0)) + (CAB.VLRFRETE * ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC + NVL(SBT.VLR_ST,0) + NVL(IPI.VLR_IPI,0))) / (CAB.VLRNOTA - CAB.VLRFRETE) AS TOTAL_BRUTO,
        ((ITE.QTDNEG * ITE.VLRUNIT) - ITE.VLRDESC) - NVL(DIF.VLR_DIFAL,0) AS TOTAL_LIQUIDO,
        CAB.NUNOTA
        FROM
        TGFITE ITE
        LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
        -- VLR DO DIFAL DO PRODUTO
        LEFT JOIN (SELECT
                    DIN.NUNOTA,
                    DIN.SEQUENCIA,
                    SUM(DIN.VLRDIFALDEST + VLRFCP) AS VLR_DIFAL
                    FROM TGFDIN DIN
                    GROUP BY
                    DIN.NUNOTA,
                    DIN.SEQUENCIA
                    ) DIF ON DIF.NUNOTA = ITE.NUNOTA AND DIF.SEQUENCIA = ITE.SEQUENCIA
        -- VLR DO ST DO PRODUTO
        LEFT JOIN (SELECT
                    DIN.NUNOTA,
                    DIN.SEQUENCIA,
                    SUM(DIN.VALOR + VLRFCPINT) AS VLR_ST
                    FROM TGFDIN DIN
                    WHERE DIN.CODIMP = '2'
                    GROUP BY
                    DIN.NUNOTA,
                    DIN.SEQUENCIA
                    ) SBT ON SBT.NUNOTA = ITE.NUNOTA AND SBT.SEQUENCIA = ITE.SEQUENCIA
        -- VLR DO IPI DO PRODUTO
        LEFT JOIN (SELECT
                    DIN.NUNOTA,
                    DIN.SEQUENCIA,
                    SUM(DIN.VALOR) AS VLR_IPI
                    FROM TGFDIN DIN
                    WHERE DIN.CODIMP = '3'
                    GROUP BY
                    DIN.NUNOTA,
                    DIN.SEQUENCIA
                    ) IPI ON IPI.NUNOTA = ITE.NUNOTA AND IPI.SEQUENCIA = ITE.SEQUENCIA
        WHERE
        CAB.CODTIPOPER IN ('3200','3205','3262','3220')
        AND ITE.CODPROD NOT IN ('3335','3337','3988','10435','14445','15887','16136','16137','16098','15892','3189','3004','4053','4341','16135')
    ) AAA
    GROUP BY 
AAA.NUNOTA) ONM ON CAB.NUNOTA = ONM.NUNOTA

WHERE
CAB.CODTIPOPER IN ('3200','3205','3262','3220')
AND CAB.DTNEG BETWEEN '01/10/2025' AND '31/10/2025'
) FIN
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = FIN.CODVEND

GROUP BY
FIN.CODVEND,
VEN.APELIDO