SELECT
DECODE(CAC.CODEMP,'1','KLG COM. IMP. E EXP. DE PEÇAS LTDA - 07.492.452/0001-87','2','KLG IND. E COM. DE MAQUINAS LTDA - 32.719.392/0001-30','3','KLG COM. IMP. E EXP. DE PEÇAS EIRELI - 07.492.452/0002-68','4','KLG COM. IMP. E EXP. DE PEÇAS LTDA - 07.492.452/0003-49') AS EMP,
PAR.CODPARC,
PAR.RAZAOSOCIAL,
PAR.NUMEND,
ENR.NOMEEND,
PAR.COMPLEMENTO,
BAI.NOMEBAI,
PAR.AD_UF,
PAR.CEP,
PAR.TELEFONE,
PAR.FAX,
PAR.EMAIL,
PAR.DTNASC,
PAR.AD_ETNIA,
PAR.SEXO,
DECODE(PAR.AD_ESTD_CIVIL,'S','SOLTEIRO','C','CASADO','D','DIVORCIADO','V','VIÚVO','U','UNIÃO ESTÁVEL','O','OUTROS') AS ESTADO_CIVIL,
CPL.MAE,
CPL.PAI,
PAI.DESCRICAO,
CID.NOMECID,
DECODE(PAR.AD_GRAU_INST,'1','Analfabeto','2','Até a 4º série incompleta do ensino fundamental','3','4º série completa do ensino fundamenta','4','Da 5º a 8º série do ensino fundamental','5','Ensino fundamental completo','6','Ensino médio incompleto','7','Ensino médico completo','8','Educação Superior incompleta','9','Educação Superior completa','10','Pós Graduação','11','Mestrado','12','Doutorado') AS GRAU_DE_INSTRUCAO,
PAR.AD_FORM_ACAD,
PAR.AD_CTPS,
PAR.AD_TIT_ELEI,
PAR.AD_PIS,
PAR.IDENTINSCESTAD,
PAR.CGC_CPF,
CPL.NROCNH,
CPL.CATEGORIACNH,
CPL.VENCIMENTOCNH,
PAR.AD_CNH_DT_EX,
PAR.AD_CNH_DT_1,
PAR.AD_ORG_CNH,
PAR.AD_NMCONSREG,
PAR.AD_SIGCONSREG,
PAR.AD_NUMCONSREG,
PAR.AD_REGCONSREG,
PAR.AD_DTCONSREG,
PAR.AD_ORGCONSREG,
PAR.AD_DTCONSREGVENC,
PAR.CODBCO,
BCO.NOMEBCO,
PAR.CODAGE,
PAR.AD_TIPO_CONTA,
PAR.CODCTABCO,
PAR.AD_CNPJ_EMPANT,
PAR.AD_MAT_EMPANT,
PAR.AD_DT_EMPANT,
PAR.AD_DES_EMPANT,
PAR.AD_CERTIDAO,
PAR.AD_DT_CONTRAT,
'SEGUNDA A SEXTA' AS DIAS_TRABALHADOS,
TO_CHAR(TO_TIMESTAMP(TO_CHAR(PAR.AD_EXP_INI, '0000'), 'HH24:MI'),'HH24:MI') || ' - ' || TO_CHAR(TO_TIMESTAMP(TO_CHAR(PAR.AD_EXP_FIN, '0000'), 'HH24:MI'),'HH24:MI') AS EXPEDIENTE,
TO_CHAR(TO_TIMESTAMP(TO_CHAR(PAR.AD_INT_INI, '0000'), 'HH24:MI'),'HH24:MI') || ' - ' || TO_CHAR(TO_TIMESTAMP(TO_CHAR(PAR.AD_INT_FIN, '0000'), 'HH24:MI'),'HH24:MI') AS INTERVALO,
DECODE(PAR.AD_VT,'S','SIM','N','NÃO','','NÃO') AS VALE_TRASNP,
'SIM' AS DESCONTA_VT,
PAR.AD_VT_QTD,
PAR.AD_VT_TIPO,
PAR.AD_VT_VLR,
CAC.CARGO,
CAC.SALARIO,
DPP.NOME,
DPP.AD_DT_NASC,
DPP.AD_NATURAL,
DPP.CPF,
DPP.AD_CERTIDAO,
DPP.RELACIONAMENTO,
DECODE(DPP.DEPENDIR,'S','SIM','N','NÃO','','NÃO') AS DEP_IR

FROM
TGFPAR PAR
LEFT JOIN TGFCPL CPL ON CPL.CODPARC = PAR.CODPARC
LEFT JOIN TSIEND ENR ON ENR.CODEND = PAR.CODEND
LEFT JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI
LEFT JOIN TSIBCO BCO ON BCO.CODBCO = PAR.CODBCO
LEFT JOIN TSICID CID ON CID.CODCID = CPL.NATURALIDADE
LEFT JOIN TSIPAI PAI ON PAI.CODPAIS = PAR.AD_NACIONALIDADE
LEFT JOIN (SELECT MAX(ID_CARCOL) AS ID, CODPARC
FROM AD_CARCOL GROUP BY CODPARC) MXC ON MXC.CODPARC = PAR.CODPARC
LEFT JOIN AD_CARCOL CAC ON CAC.ID_CARCOL = MXC.ID AND CAC.CODPARC = PAR.CODPARC
LEFT JOIN TGFDPP DPP ON DPP.CODPARC = PAR.CODPARC

WHERE PAR.CODPARC = '2425'