SELECT
AAA.CODIGO,
AAA.DESCRICAO,
AAA.UNIDADE,
AAA.NCM,
AAA.TIPO,
AAA.QTD,
AAA.CUSTO_UNITARIO,
(AAA.QTD * AAA.CUSTO_UNITARIO) AS CUSTO_TOTAL
FROM
(SELECT 
PRO.CODPROD AS CODIGO,
PRO.DESCRPROD AS DESCRICAO,
CTE.CODVOL AS UNIDADE,
PRO.NCM AS NCM,
CTE.TIPO AS TIPO,
SUM (CTE.QTDEST) AS QTD,
CUS.CUSREP AS CUSTO_UNITARIO
FROM 
    TGFPRO PRO
    LEFT JOIN TGFCTE CTE ON PRO.CODPROD = CTE.CODPROD,
    (SELECT DISTINCT(DDD.CODPROD) AS CODPROD,MAX(CUS.CUSREP) AS CUSREP, CUS.DTATUAL AS DATA
    FROM (SELECT MAX (EEE.DTATUAL) AS DATA, EEE.CODPROD, EEE.CODPROD || MAX (EEE.DTATUAL) AS VALID
            FROM TGFCUS EEE GROUP BY EEE.CODPROD) DDD
        LEFT JOIN TGFCUS CUS ON DDD.VALID = CUS.CODPROD || CUS.DTATUAL
        GROUP BY DDD.CODPROD, CUS.DTATUAL) CUS
WHERE
PRO.USOPROD IN ('R','M','2','P')
AND PRO.CODPROD = CUS.CODPROD
AND PRO.AD_COD_EX IS NULL
AND CTE.CODEMP = :EMP
AND CTE.DTCONTAGEM = :DT_CONT
GROUP BY
PRO.CODPROD,
PRO.DESCRPROD,
CTE.CODVOL,
PRO.NCM,
CTE.TIPO,
CUS.CUSREP) AAA
