SELECT 
PRO.CODPROD,
PRO.DESCRPROD,
CTE.CODVOL,
PRO.NCM,
CTE.TIPO,
PRO.USOPROD,
CTE.CODEMP,
SUM (CTE.QTDEST),
CUS.CUSGER
FROM 
    TGFPRO PRO
    LEFT JOIN TGFCTE CTE ON PRO.CODPROD = CTE.CODPROD,
    TGFCUS CUS,
    (SELECT 
    MAX (EEE.DTATUAL) AS DATA,
    EEE.CODPROD
    FROM TGFCUS EEE
    GROUP BY
    EEE.CODPROD
    ) DDD
WHERE
DDD.CODPROD = PRO.CODPROD
AND DDD.CODPROD = CUS.CODPROD
AND DDD.DATA = CUS.DTATUAL
AND PRO.USOPROD IN ('R','M','2','P')
AND CTE.CODEMP = '1'
AND CTE.DTCONTAGEM = '31/12/2021'

GROUP BY
PRO.CODPROD,
PRO.DESCRPROD,
CTE.CODVOL,
PRO.NCM,
CTE.TIPO,
PRO.USOPROD,
CTE.CODEMP,
CUS.CUSGER
