SELECT
ITE.CODPROD AS COD,
PRO.DESCRPROD AS PRODUTO,
NVL(ITE.QTD_AG, 0) + NVL(QTD_SUG, 0) AS QUANTIDADE,
DET.UN_PRC + NVL(UN_ADJ, 0) - NVL(UN_DESC, 0) AS PRECO,
DET.CODPARC AS COD_FORN,
PAR.RAZAOSOCIAL AS FORNECEDOR

FROM
AD_ITELIS ITE
LEFT JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
LEFT JOIN AD_DETPRC DET ON DET.ID = ITE.ID AND DET.SEQ = ITE.SEQ
LEFT JOIN TGFPAR PAR ON DET.CODPARC = PAR.CODPARC

WHERE
ITE.ID = '7'

ORDER BY
ITE.CODPROD
