SELECT
FIN.NUNOTA,
FIN.VLRMULTA + FIN.VLRJURO AS VLR,
FIN.DHBAIXA,
FIN.RECDESP

FROM
TGFFIN FIN

WHERE
FIN.DHBAIXA IS NOT NULL
AND FIN.RECDESP = 1
AND FIN.PROVISAO = 'N'
AND (FIN.DHBAIXA - FIN.DTVENC) > 4
AND FIN.VLRJURO > 0 
OR FIN.VLRMULTA > 0
AND FIN.DHBAIXA IS NOT NULL
AND FIN.RECDESP = 1
AND FIN.PROVISAO = 'N'
AND (FIN.DHBAIXA - FIN.DTVENC) > 4