SELECT 
PRO.CODPROD AS CORG, PRO.DESCRPROD AS NOME_MATRIZ, PAL.CODPRODALT AS CALT
FROM 
TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
WHERE 
PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL
UNION ALL SELECT 
PRO.CODPROD, PRO.DESCRPROD AS NOME_MATRIZ, PRO.CODPROD AS CODPRODALT
FROM 
TGFPRO PRO 
WHERE 
PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M'