SELECT
VMD.CODPROD,
VMD.DESCRPROD,
VMD.AD_TIP_ALT,
VMD.VLR_UNIT_LIQ,
PAL.CODPROD AS CODMAT

FROM
(SELECT
VLV.CODPROD,
VLV.DESCRPROD,
VLV.AD_TIP_ALT,
AVG(VLV.VLR_UNIT_LIQ) AS VLR_UNIT_LIQ
FROM
(SELECT
ITE.CODPROD,
PRO.DESCRPROD,
PRO.AD_TIP_ALT,
ITE.VLRUNIT - (ITE.VLRDESC * ITE.QTDNEG) + (ITE.VLRSUBST / ITE.QTDNEG) + (ITE.VLRIPI / ITE.QTDNEG) AS VLR_UNIT_LIQ,
ITE.NUNOTA
FROM
TGFITE ITE
LEFT JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE
CAB.CODTIPOPER IN ('3200','3205')
AND CAB.DTNEG > '28/02/2023') VLV
GROUP BY
VLV.CODPROD,
VLV.DESCRPROD,
VLV.AD_TIP_ALT) VMD
LEFT JOIN TGFPAL PAL ON PAL.CODPRODALT = VMD.CODPROD

