SELECT
(VVV.VLRTOT / DRS.DIAS_REST) AS META_RESTANTE
FROM
(SELECT
    VEN.CODVEND,
    AD_META - SUM(CAB.VLRNOTA) AS VLRTOT
    FROM
    TGFCAB CAB
    LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
    LEFT JOIN TSIUSU USU ON CAB.CODVEND = USU.CODVEND
    WHERE 
    LTRIM(TO_CHAR(DTMOV, 'mm-yyyy'), '0') = LTRIM(TO_CHAR(CURRENT_DATE, 'mm-yyyy'), '0') 
    AND CAB.CODTIPOPER IN ('3101','3102','3104')
    AND USU.CODUSU = '57'
    GROUP BY 
    VEN.CODVEND,
    VEN.AD_META) VVV,
(SELECT DIA.DIAS - FER.AD_DIA AS DIAS_REST
    FROM TSIFER FER,
    (SELECT COUNT(FER.AD_DIA) AS DIAS FROM TSIFER FER WHERE FER.AD_UTIL = 'S') DIA
    WHERE FER.AD_DIA = LTRIM(TO_CHAR(CURRENT_DATE, 'dd'), '0')) DRS
