SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM(ITE.QTDNEG) AS QTD

FROM
TGFITE ITE
LEFT JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA

WHERE
CAB.CODEMP IN ('1','2','3')
AND CAB.DTNEG BETWEEN '01/03/2022' AND '30/06/2022'
AND CAB.CODTIPOPER = '3100'
AND ITE.NUFOP = '1'
AND CAB.AD_UF IN ('Acre','Amapá','Amazonas','Pará','Rondônia','Roraima','Tocantins','Alagoas','Bahia','Ceará','Maranhão','Paraíba','Piauí','Pernambuco','Rio Grande do Norte','Sergipe')

GROUP BY 
ITE.CODPROD,
PRO.DESCRPROD