SELECT
CAB.NUNOTA,
CAB.AD_INVOICE,
CAB.VLRMOEDA,
VLRTOTLIQITEMMOE,
AAA.ADJ AS AJUSTE,
CAB.AD_ANTC_1,
CAB.AD_1_CONTRACT,
CAB.AD_ANTC_1_DT,
CAB.AD_NOTE_CAMB_1,
CAB.AD_ANTC_2,
CAB.AD_2_CONTRACT,
CAB.AD_ANTC_2_DT,
CAB.AD_NOTE_CAMB_2,
CAB.AD_ANTC_3,
CAB.AD_3_CONTRACT,
CAB.AD_ANTC_3_DT,
CAB.AD_NOTE_CAMB_3,
CAB.AD_ANTC_4,
CAB.AD_4_CONTRACT,
CAB.AD_ANTC_4_DT,
CAB.AD_NOTE_CAMB_4,
CAB.AD_ANTC_5,
CAB.AD_5_CONTRACT,
CAB.AD_ANTC_5_DT,
CAB.AD_NOTE_CAMB_5,
PRJ.IDENTIFICACAO

FROM
TGFCAB CAB
LEFT JOIN (SELECT
III.NUNOTA,
SUM(III.AJUSTE) AS ADJ
FROM
TGFCAB CAB
LEFT JOIN (SELECT
    ITE.NUNOTA,
    ITE.CODPROD,
    (ITE.AD_VLR_DESC_ADJ_USD * ITE.QTDNEG) AS AJUSTE
    FROM
    TGFITE ITE
    WHERE
    ITE.AD_VLR_DESC_ADJ_USD IS NOT NULL) III ON CAB.NUNOTA = III.NUNOTA
GROUP BY
III.NUNOTA) AAA ON CAB.NUNOTA = AAA.NUNOTA
LEFT JOIN TCSPRJ PRJ ON CAB.CODPROJ = PRJ.CODPROJ

WHERE
CAB.CODTIPOPER = '2000'
AND CAB.DTNEG > '01/04/2021'