SELECT
PRO.CODPROD,
PRO.DESCRPROD,
PRO.MARGLUCRO,
((100/(1-(PRO.MARGLUCRO / 100)))/100) AS COEF,
CUS.CUSREP


FROM
TGFPRO PRO
LEFT JOIN (SELECT 
DISTINCT(DDD.CODPROD) AS CODPROD,
MAX(CUS.CUSREP) AS CUSREP, 
CUS.DTATUAL AS DATA
    FROM (SELECT MAX (EEE.DTATUAL) AS DATA,
     EEE.CODPROD,
     EEE.CODPROD || MAX (EEE.DTATUAL) AS VALID
            FROM TGFCUS EEE GROUP BY EEE.CODPROD) DDD
        LEFT JOIN TGFCUS CUS ON DDD.VALID = CUS.CODPROD || CUS.DTATUAL
        GROUP BY DDD.CODPROD, CUS.DTATUAL) CUS ON PRO.CODPROD = CUS.CODPROD

WHERE
PRO.USOPROD = 'R' AND
PRO.ATIVO = 'S' AND
PRO.AD_COD_EX IS NULL