SELECT
PRO.CODPROD,
PRO.DESCRPROD,
AAA.CODEMP,
CURRENT_DATE - AAA.DATA AS DIAS
FROM
TGFPRO PRO
LEFT JOIN(SELECT
ITE.CODPROD,
CAB.CODEMP,
MAX(CAB.DTNEG) AS DATA
FROM
TGFITE ITE
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
WHERE
CAB.CODTIPOPER = '2106'
GROUP BY 
ITE.CODPROD,
CAB.CODEMP) AAA ON AAA.CODPROD = PRO.CODPROD
WHERE
PRO.USOPROD = 'R' AND CURRENT_DATE - AAA.DATA IS NOT NULL

