SELECT
PRO.CODPROD,
PRO.DESCRPROD AS NOME_MATRIZ,
PRO.AD_CODMATRIZ,
PRO.AD_TIP_ALT = 'M',
PAL.CODPRODALT,
NOM.DESCRPROD AS NOME_ALTER

FROM
TGFPRO PRO
LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
LEFT JOIN TGFPRO NOM ON PAL.CODPRODALT = NOM.CODPROD

WHERE
PRO.USOPROD = 'R'
AND PRO.AD_COD_EX IS NULL