SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM(ITE.QTDNEG)

FROM
TGFITE ITE 
JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA 
JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD

WHERE
PRO.USOPROD IN ('R') AND
CAB.DTNEG >= '01/01/2021' AND -- Dt Inicio
CAB.DTNEG <= '08/10/2021' AND -- Dt Fim
CAB.CODTIPOPER IN ('3200','3205')

GROUP BY
ITE.CODPROD,
PRO.DESCRPROD