SELECT
IXN.NUMNOTA AS NF,
IXN.CODEMP AS EMPRESA,
IXN.DHEMISS AS DT_EMISSAO,
IXN.CNPJPARC AS CNPJ_EMITENTE,
DECODE(IXN.STATUS,'0','PENDENTE','1','CANCELADO','2','IMPORTADO','4','COM DIVERGENCIA','5','CONFIRMADO') AS STATUS_PORTAL,
DECODE(IXN.SITUACAONFE,'1','USO AUTORIZADO','3','CANCELADO') AS SITUACAO_NOTA,
DECODE(IXN.SITUACAOMDE,'1','OPERACAO CONFIRMADA','3','OPERACAO NÃO REALIZADA','4','CIENCIA','7','PREST. SERV. EM DESACORDO') AS SITUCAO_MANIFESTO

FROM
TGFIXN IXN
LEFT JOIN TGFPAR PAR ON IXN.CNPJPARC = PAR.CGC_CPF

WHERE 
IXN.DHEMISS > '30/04/2023'