SELECT
PAR.CODPARC,
PAR.RAZAOSOCIAL,
TPP.DESCRTIPPARC,
FAT.TOTAL,
(FAT.TOTAL / FAT.QTD) AS TICKET,
PAR.AD_XCMG,
PAR.AD_XCMG_BR,
PAR.AD_ZOOMLION,
PAR.AD_SANY

FROM
TGFPAR PAR

LEFT JOIN (SELECT
CAB.CODPARC,
COUNT(CAB.VLRNOTA) AS QTD,
SUM(CAB.VLRNOTA) AS TOTAL
FROM
TGFCAB CAB
WHERE
CAB.CODTIPOPER IN ('3200','3250','3262')
AND CAB.CODPARC NOT IN ('1974','1883','4506','0')
GROUP BY
CAB.CODPARC) FAT ON PAR.CODPARC = FAT.CODPARC

LEFT JOIN TGFTPP TPP ON PAR.CODTIPPARC = TPP.CODTIPPARC

WHERE
PAR.CLIENTE = 'S' AND PAR.ATIVO = 'S'