SELECT
PPP.CODPROD,
PPP.CUSREP

FROM
(SELECT
    MAX(DATA) AS DATA,
    AAA.CODPROD
    FROM
    (SELECT
    ZZZ.CODPROD,
    ZZZ.NOME_MATRIZ,
    ZZZ.CODPRODALT,
    ZZZ.NOME_ALTER,
    CCC.CUSREP,
    CCC.DATA
    FROM
    (SELECT
        PRO.CODPROD,
        PRO.DESCRPROD AS NOME_MATRIZ,
        PRO.AD_CODMATRIZ,
        PAL.CODPRODALT,
        NOM.DESCRPROD AS NOME_ALTER
        FROM
        TGFPRO PRO
        LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
        LEFT JOIN TGFPRO NOM ON PAL.CODPRODALT = NOM.CODPROD
        WHERE
        PRO.USOPROD = 'M'
        AND PRO.AD_COD_EX IS NULL
        AND PRO.AD_CODMATRIZ = 'S'
        UNION ALL
        SELECT
        PRO.CODPROD,
        PRO.DESCRPROD AS NOME_MATRIZ,
        PRO.AD_CODMATRIZ,
        PRO.CODPROD,
        PRO.DESCRPROD AS NOME_ALTER
        FROM
        TGFPRO PRO
        WHERE
        PRO.USOPROD = 'M'
        AND PRO.AD_COD_EX IS NULL
        AND PRO.AD_CODMATRIZ = 'S') ZZZ
    LEFT JOIN (SELECT 
        DDD.CODPROD,
        CUS.CUSREP,
        DDD.DATA
        FROM TGFCUS CUS,
        (SELECT 
            MAX (EEE.DTATUAL) AS DATA,
            EEE.CODPROD
            FROM TGFCUS EEE
            GROUP BY
            EEE.CODPROD) DDD
        WHERE
        DDD.CODPROD = CUS.CODPROD
        AND DDD.DATA = CUS.DTATUAL) CCC ON CCC.CODPROD = ZZZ.CODPRODALT
    WHERE ZZZ.CODPRODALT IS NOT NULL) AAA
    GROUP BY
    AAA.CODPROD) DDD

LEFT JOIN (SELECT
    ZZZ.CODPROD,
    ZZZ.NOME_MATRIZ,
    CCC.CUSREP,
    CCC.DATA
    FROM
    (SELECT
        PRO.CODPROD,
        PRO.DESCRPROD AS NOME_MATRIZ,
        PRO.AD_CODMATRIZ,
        PAL.CODPRODALT,
        NOM.DESCRPROD AS NOME_ALTER
        FROM
        TGFPRO PRO
        LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
        LEFT JOIN TGFPRO NOM ON PAL.CODPRODALT = NOM.CODPROD
        WHERE
        PRO.USOPROD = 'M'
        AND PRO.AD_COD_EX IS NULL
        AND PRO.AD_CODMATRIZ = 'S'
        UNION ALL
        SELECT
        PRO.CODPROD,
        PRO.DESCRPROD AS NOME_MATRIZ,
        PRO.AD_CODMATRIZ,
        PRO.CODPROD,
        PRO.DESCRPROD AS NOME_ALTER
        FROM
        TGFPRO PRO
        WHERE
        PRO.USOPROD = 'M'
        AND PRO.AD_COD_EX IS NULL
        AND PRO.AD_CODMATRIZ = 'S') ZZZ
    LEFT JOIN (SELECT 
        DDD.CODPROD,
        CUS.CUSREP,
        DDD.DATA
        FROM TGFCUS CUS,
        (SELECT 
            MAX (EEE.DTATUAL) AS DATA,
            EEE.CODPROD
            FROM TGFCUS EEE
            GROUP BY
            EEE.CODPROD) DDD
        WHERE
        DDD.CODPROD = CUS.CODPROD
        AND DDD.DATA = CUS.DTATUAL) CCC ON CCC.CODPROD = ZZZ.CODPRODALT
    WHERE ZZZ.CODPRODALT IS NOT NULL) PPP ON DDD.CODPROD = PPP.CODPROD 
    
    
WHERE PPP.DATA = DDD.DATA
