SELECT
ITE.CODPROD,
PRO.DESCRPROD,
CAB.DTNEG,
ITE.QTDNEG
FROM
TGFITE ITE
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
LEFT JOIN (SELECT
MAX(CAB.NUNOTA) AS NUNOTA,
LIG.CORG AS CODPROD
FROM
TGFCAB CAB
LEFT JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN (SELECT 
    PRO.CODPROD AS CORG, PRO.DESCRPROD AS NOME_MATRIZ, PAL.CODPRODALT AS CALT
    FROM 
    TGFPRO PRO LEFT JOIN TGFPAL PAL ON PAL.CODPROD = PRO.CODPROD
    WHERE 
    PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M' AND PAL.CODPRODALT IS NOT NULL
    UNION ALL SELECT 
    PRO.CODPROD, PRO.DESCRPROD AS NOME_MATRIZ, PRO.CODPROD AS CODPRODALT
    FROM 
    TGFPRO PRO 
    WHERE 
    PRO.USOPROD = 'R' AND PRO.AD_COD_EX IS NULL AND PRO.AD_TIP_ALT = 'M') LIG ON LIG.CALT = ITE.CODPROD

WHERE
CAB.CODTIPOPER = '2106'
AND CAB.DTNEG < '01/08/2025'
GROUP BY
LIG.CORG) NUM ON ITE.NUNOTA = NUM.NUNOTA AND ITE.CODPROD = NUM.CODPROD

WHERE
ITE.NUNOTA = NUM.NUNOTA