SELECT
SUM(CAB.VLRNOTA) AS VENDA,
PAR.AD_UF,
LTRIM(TO_CHAR(CAB.DTNEG, 'mm/yyyy'), '0') AS PERIODO

FROM
TGFCAB CAB
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC

WHERE
CAB.CODTIPOPER IN ('3200','3205')
AND CAB.CODEMP IN ('1','2')
AND CAB.DTNEG > '30/04/2021'
AND PAR.AD_UF IN ('Rondônia','Distrito Federal','Goiás','Espírito Santo','Mato Grosso','Minas Gerais')

GROUP BY
PAR.AD_UF,
LTRIM(TO_CHAR(CAB.DTNEG, 'mm/yyyy'), '0')