SELECT
BBB.VENDAS AS VENDAS,
BBB.PERIODO

FROM
(SELECT
SUM(AAA.VENDAS) AS VENDAS,
AAA.PERIODO

FROM
(SELECT
CAB.VLRNOTA AS VENDAS,
LTRIM(TO_CHAR(CAB.DTNEG, 'mm/yyyy'), '0') AS PERIODO

FROM
TGFCAB CAB,
(SELECT DISTINCT(ITE.NUNOTA) AS NUNOTA
FROM TGFPRO PRO  
LEFT JOIN TGFITE ITE ON ITE.CODPROD = PRO.CODPROD 
LEFT JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
WHERE PRO.USOPROD IN ('2','V') AND CAB.CODTIPOPER IN ('3200','3205','3250','3262')) CCC

WHERE
CAB.CODEMP = '2' AND
CCC.NUNOTA = CAB.NUNOTA AND
CAB.CODTIPOPER IN ('3200','3205','3250','3262')) AAA

GROUP BY
AAA.PERIODO) BBB

