SELECT
ITE.CODPROD,
PRO.DESCRPROD,
SUM (ITE.QTDNEG)

FROM
TGFITE ITE
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD

WHERE
CAB.AD_UF ('Alagoas','Bahia','Ceará','Maranhão','Paraíba','Piauí','Pernambuco','Rio Grande do Norte','Sergipe','Acre','Amapá','Amazonas','Pará','Rondônia','Roraima','Tocantins')
AND CAB.CODTIPOPER IN ('3200','3205')
AND CAB.DTNEG BETWEEN '01/03/2022' AND '30/06/2022'
AND PRO.DESCRPROD LIKE 'CABO DE AÇO'

GROUP BY
ITE.CODPROD,
PRO.DESCRPROD