SELECT
VEN.APELIDO,
SUM(CAB.VLRNOTA) AS VLRTOT

FROM
TGFCAB CAB
LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND

WHERE 
CAB.DTNEG = CURRENT_DATE
AND CAB.CODTIPOPER IN ('3101','3102')

GROUP BY 
VEN.APELIDO