SELECT
AAA.CODPROD,
AAA.DESCRPROD,
SUM(AAA.QTD_COMP) AS QTD_COMP,
AAA.DT_COMP,
AAA.QTD_VEND,
AAA.DT_VEN,
AVG(AAA.CUSREP) AS CUSREP

FROM
(SELECT
COM.CODPROD,
COM.DESCRPROD,
COM.CONTROLE,
COM.QTDNEG AS QTD_COMP,
COM.DTNEG AS DT_COMP,
SUM(VEN.QTD_VEND) AS QTD_VEND,
MAX(VEN.DTNEG) AS DT_VEN,
CCT.CUSREP
FROM 
(SELECT
    ITE.CODPROD,
    PRO.DESCRPROD,
    ITE.CONTROLE,
    ITE.QTDNEG,
    CAB.DTNEG
    FROM
    TGFITE ITE
    LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
    LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
    WHERE
    /* Filtro da Importação*/
    CAB.NUNOTA IN ('180692','180670','180679')) COM
LEFT JOIN (SELECT
    ITE.CODPROD,
    PRO.DESCRPROD,
    SUM(ITE.QTDNEG) AS QTD_VEND,
    CAB.DTNEG
    FROM
    TGFITE ITE
    LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
    LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
    WHERE
    CAB.CODTIPOPER IN ('3200','3210')
    GROUP BY
    ITE.CODPROD,
    PRO.DESCRPROD,
    CAB.DTNEG) VEN ON VEN.CODPROD = COM.CODPROD AND VEN.DTNEG BETWEEN COM.DTNEG AND (COM.DTNEG + 30)
LEFT JOIN (SELECT 
    DDD.CONTROLE,
    DDD.CODPROD,
    CUS.CUSREP
    FROM TGFCUS CUS,
    (SELECT 
    MAX (EEE.DTATUAL) AS DATA,
    EEE.CONTROLE,
    EEE.CODPROD
    FROM TGFCUS EEE
    GROUP BY
    EEE.CONTROLE,
    EEE.CODPROD
    ) DDD
    WHERE
    DDD.CONTROLE = CUS.CONTROLE
    AND DDD.CODPROD = CUS.CODPROD
    AND DDD.DATA = CUS.DTATUAL
    ) CCT ON COM.CODPROD = CCT.CODPROD AND CCT.CONTROLE = COM.CONTROLE
GROUP BY
COM.CODPROD,
COM.DESCRPROD,
COM.CONTROLE,
COM.QTDNEG,
COM.DTNEG,
CCT.CUSREP) AAA

GROUP BY
AAA.CODPROD,
AAA.DESCRPROD,
AAA.DT_COMP,
AAA.QTD_VEND,
AAA.DT_VEN