SELECT
SUM(CAB.VLRNOTA) AS FAT,
SUM(CAB.VLRFRETE) AS FRETE,
SUM(III.VLRIMP) AS IMPOSTOS,
SUM(CCC.CUSTO) AS CUSTO,
((SUM(CAB.VLRNOTA) - SUM(CAB.VLRFRETE) - SUM(CCC.CUSTO) - SUM(III.VLRIMP)) / SUM(CAB.VLRNOTA) * 100) AS MC,
CAB.AD_UF

FROM
TGFCAB CAB
LEFT JOIN (SELECT
        DIN.NUNOTA,
        SUM(DIN.VALOR + DIN.VLRDIFALDEST + VLRFCP) AS VLRIMP
        FROM
        TGFDIN DIN
        GROUP BY
        DIN.NUNOTA
        ) III ON CAB.NUNOTA = III.NUNOTA
LEFT JOIN (SELECT
CC3.NUNOTA,
SUM(CC3.CALC) AS CUSTO
FROM
(SELECT
    ITE.NUNOTA,
    (CC2.CUSGER * ITE.QTDNEG) AS CALC
    FROM
    TGFITE ITE
    /*Retorna o Custo*/
    LEFT JOIN (SELECT 
            DDD.CONTROLE,
            DDD.CODPROD,
            CUS.CUSGER
            FROM TGFCUS CUS,
                (SELECT 
                MAX (EEE.DTATUAL) AS DATA,
                EEE.CONTROLE,
                EEE.CODPROD
                FROM TGFCUS EEE
                GROUP BY
                EEE.CONTROLE,
                EEE.CODPROD
                ) DDD
            WHERE
            DDD.CONTROLE = CUS.CONTROLE
            AND DDD.CODPROD = CUS.CODPROD
            AND DDD.DATA = CUS.DTATUAL
            )CC2 ON ITE.CODPROD = CC2.CODPROD AND ITE.CONTROLE = CC2.CONTROLE
    )CC3
    GROUP BY
    CC3.NUNOTA
    ) CCC ON CAB.NUNOTA = CCC.NUNOTA

WHERE
CAB.CODTIPOPER IN ('3200','3205')
AND CAB.DTNEG BETWEEN '01/10/2021' AND '19/10/2023'

GROUP BY
CAB.AD_UF