SELECT
CCC.CODPARC AS COD,
CCC.RAZAOSOCIAL AS CLIENTE,
CCC.TOTAL,
CCC.APELIDO AS VENDEDOR_ATUAL,
ROUND(CCC.DIAS_S_COMPRA) AS DIAS_S_COMPRA,
CCC.ULT_COMPRA,
BBB.NUNOTA AS ULT_ORC,
BBB.DTNEG AS DT_ULT_ORC,
BBB.NOME_VEND_ULT_ORC AS VENDEDOR_ORCAMENTO

FROM
(SELECT
CAB.CODPARC,
PAR.RAZAOSOCIAL,
SUM(CAB.VLRNOTA) AS TOTAL,
PAR.CODVEND,
VEN.APELIDO,
ROUND(CURRENT_DATE - MAX(CAB.DTNEG)) AS DIAS_S_COMPRA,
MAX(CAB.DTNEG) AS ULT_COMPRA
FROM
TGFCAB CAB
LEFT JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = PAR.CODVEND
WHERE
CAB.DTNEG >= '12/03/2023'
AND CAB.CODTIPOPER IN ('3200','3250','3205')
GROUP BY
CAB.CODPARC,
PAR.RAZAOSOCIAL,
PAR.CODVEND,
VEN.APELIDO) CCC

LEFT JOIN (SELECT
CAB.CODPARC,
CAB.NUNOTA,
CAB.DTNEG,
CAB.CODVEND AS VEND_ULT_ORC,
VEN.APELIDO AS NOME_VEND_ULT_ORC
FROM
TGFCAB CAB
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
LEFT JOIN (SELECT
CAB.CODPARC,
MAX(CAB.NUNOTA) AS ULT_ORC
FROM
TGFCAB CAB
WHERE
CAB.CODTIPOPER IN ('3100','3103','3109')
GROUP BY
CAB.CODPARC) AAA ON AAA.ULT_ORC = CAB.NUNOTA
WHERE
AAA.ULT_ORC IS NOT NULL) BBB ON BBB.CODPARC = CCC.CODPARC
