#type.sql# 
SELECT 
TGFPAR.RAZAOSOCIAL

FROM TGFCAB CAB
JOIN TGFPAR ON TGFCAB.CODPARCTRANSP = TGFPAR.CODPARC

WHERE
CAB.CODTIPOPER IN (3200, 3205, 3250, 3262) 
AND CAB.CODPARC = TGFCAB.CODPARC
AND CAB.DTNEG = (SELECT MAX(CAB.DTNEG) FROM TGFCAB CAB JOIN TGFPAR ON CAB.CODPARC = TGFPAR.CODPARC
WHERE CAB.CODTIPOPER IN (3200, 3205, 3250, 3262)  AND CAB.CODPARC=TGFPAR.CODPARC)





SELECT 
DECODE(TGFCAB.CIF_FOB,'C','CIF','F','FOB','S','SEM FRETE','T','TERCEIRO')

FROM TGFCAB 
JOIN TGFPAR ON TGFCAB.CODPARC = TGFPAR.CODPARC

WHERE
TGFCAB.CODTIPOPER IN (3200, 3205, 3250, 3262) 
AND TGFCAB.CODPARC = ${CODPARC}
AND TGFCAB.DTNEG = (SELECT MAX(TGFCAB.DTNEG) FROM TGFCAB JOIN TGFPAR ON TGFCAB.CODPARC = TGFPAR.CODPARC
WHERE TGFCAB.CODTIPOPER IN (3200, 3205, 3250, 3262)  AND TGFCAB.CODPARC=TGFPAR.CODPARC)