#type.sql# 
(SELECT
CASE 
WHEN TTT.QTD > CCC.QTD THEN 'DIVERGENTE'
WHEN TTT.QTD = CCC.QTD THEN 'CONFERIDO'
WHEN CCC.QTD IS NULL THEN 'DIVERGENTE'
ELSE 'DIVERGENTE' END AS CONFERENCIA

FROM
(SELECT
COUNT(ITE.CODPROD) AS QTD,
ITE.NUNOTA
FROM
TGFITE ITE 
WHERE
ITE.NUNOTA = TGFCAB.NUNOTA
GROUP BY
ITE.NUNOTA) TTT

LEFT JOIN (SELECT
COUNT(ITE.CODPROD) AS QTD,
ITE.NUNOTA
FROM
TGFITE ITE 
WHERE
ITE.NUNOTA = TGFCAB.NUNOTA
AND ITE.AD_CONF_PL = 'S'
GROUP BY
ITE.NUNOTA) CCC ON CCC.NUNOTA = TTT.NUNOTA)


