#type.sql#
SELECT
(((AAA.VLRNOTA-AAA.AD_DESP_AT-AAA.VLRFRETE-IMP_SERV-IMP_PEC-AAA.VLRST-AAA.CUSTO)*100)/AAA.VLRNOTA) AS MC




FROM
(SELECT
NVL(CAB.AD_DESP_AT,0) AS AD_DESP_AT,
CAB.VLRNOTA,
NVL(CAB.VLRFRETE,0) AS VLRFRETE,
(ISS.VLRSERV * (ISS.ALIQ_SERV/100)) AS IMP_SERV,
(IPP.VLRPEC * (IPP.ALIQ_PEC/100)) AS IMP_PEC,
NVL(III.VLRIMP,0) AS VLRST,
CCC.CUSTO

FROM
TGFCAB CAB
LEFT JOIN(SELECT
    SUM(ITE.VLRTOT) AS VLRSERV,
    ITE.NUNOTA,
    PSN.ALIQUOTA AS ALIQ_SERV
    FROM
    TGFITE ITE,
    TGFPRO PRO,
    TGFPSN PSN
    WHERE
    ITE.CODPROD = PRO.CODPROD
    AND ITE.NUNOTA = TGFCAB.NUNOTA
    AND PRO.USOPROD = 'S'
    AND PSN.NUPARTILHA = (SELECT
    MAX(PSN.NUPARTILHA)
    FROM
    TGFPSN PSN
    WHERE
    PSN.TIPOSN = '3')
    GROUP BY
    ITE.NUNOTA,
    PSN.ALIQUOTA) ISS ON CAB.NUNOTA = ISS.NUNOTA
    
LEFT JOIN(SELECT
    SUM(ITE.VLRTOT) AS VLRPEC,
        ITE.NUNOTA,
        PSN.ALIQUOTA AS ALIQ_PEC
    FROM
    TGFITE ITE,
    TGFPRO PRO,
    TGFPSN PSN
    WHERE
    ITE.CODPROD = PRO.CODPROD
    AND ITE.NUNOTA = TGFCAB.NUNOTA
    AND PRO.USOPROD <> 'S'
    AND PSN.NUPARTILHA = (SELECT
    MAX(PSN.NUPARTILHA)
    FROM
    TGFPSN PSN
    WHERE
    PSN.TIPOSN = '1')
    GROUP BY
    ITE.NUNOTA,
    PSN.ALIQUOTA) IPP ON CAB.NUNOTA = IPP.NUNOTA

/*Retorna ST*/
LEFT JOIN (SELECT
            DIN.NUNOTA,
            SUM(DIN.VALOR + DIN.VLRDIFALDEST + VLRFCP) AS VLRIMP
            FROM TGFDIN DIN
            WHERE
            DIN.CODIMP = '2'
            GROUP BY
            DIN.NUNOTA
            ) III ON CAB.NUNOTA = III.NUNOTA

/*Retorna o Custo vs Quantidade de Produtos*/
LEFT JOIN (SELECT
        CC3.NUNOTA,
        SUM(CC3.CALC) AS CUSTO
        FROM
        (SELECT
            ITE.NUNOTA,
            (CC2.CUSGER * ITE.QTDNEG) AS CALC
            FROM
            TGFITE ITE
            /*Retorna o Custo*/
            LEFT JOIN (SELECT 
                    DDD.CONTROLE,
                    DDD.CODPROD,
                    CUS.CUSGER
                    FROM TGFCUS CUS,
                        (SELECT 
                        MAX (EEE.DTATUAL) AS DATA,
                        EEE.CONTROLE,
                        EEE.CODPROD
                        FROM TGFCUS EEE
                        GROUP BY
                        EEE.CONTROLE,
                        EEE.CODPROD
                        ) DDD
                    WHERE
                    DDD.CONTROLE = CUS.CONTROLE
                    AND DDD.CODPROD = CUS.CODPROD
                    AND DDD.DATA = CUS.DTATUAL
                    )CC2 ON ITE.CODPROD = CC2.CODPROD AND ITE.CONTROLE = CC2.CONTROLE
        )CC3
    GROUP BY
    CC3.NUNOTA
    ) CCC ON CAB.NUNOTA = CCC.NUNOTA

WHERE
CAB.NUNOTA = TGFCAB.NUNOTA) AAA