#type.sql# 
SELECT
CASE 
WHEN III.CODPROD = '10894' THEN 'SEM OPORTUNIDADE'
ELSE 'COM OPORTUNIDADE' END AS OPRT
FROM
(SELECT
ITE.CODPROD,
ITE.NUNOTA
FROM
TGFITE ITE 
WHERE
ITE.CODPROD = '10894') III
WHERE
III.NUNOTA = TGFCAB.NUNOTA