#type.sql# 
SELECT
CASE
WHEN CAB.AD_AUTO_COM IS NULL AND CAB.AD_AUTO_FIS IS NULL AND CAB.AD_SIT_DEV_GAR IS NULL THEN 'N INIC'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS IS NULL AND CAB.AD_SIT_DEV_GAR IS NULL THEN 'AUT COM'
WHEN CAB.AD_AUTO_COM = 'N' AND CAB.AD_AUTO_FIS IS NULL AND CAB.AD_SIT_DEV_GAR IS NULL THEN 'NEG COM'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS = 'A' AND CAB.AD_SIT_DEV_GAR IS NULL THEN 'AUT FISC'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS = 'N' AND CAB.AD_SIT_DEV_GAR IS NULL THEN 'NEG FISC'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS = 'A' AND CAB.AD_SIT_DEV_GAR = 'A' THEN 'AGU CHEG'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS = 'A' AND CAB.AD_SIT_DEV_GAR = 'E' THEN 'EM ANLS'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS = 'A' AND CAB.AD_SIT_DEV_GAR = 'R' THEN 'ENT REAL'
WHEN CAB.AD_AUTO_COM = 'A' AND CAB.AD_AUTO_FIS = 'A' AND CAB.AD_SIT_DEV_GAR = 'V' THEN 'MOVIMTD'
END AS STATUS

FROM
TGFCAB CAB

WHERE
CAB.NUNOTA = TGFCAB.NUNOTA
