#type.sql# 
SELECT
TGFVEN.APELIDO

FROM TGFCAB,
TGFVEN  

WHERE
TGFCAB.CODVEND = TGFVEN.CODVEND
AND TGFCAB.CODTIPOPER IN (3200, 3205, 3250, 3262) 
AND TGFCAB.CODPARC = TGFPAR.CODPARC 
AND TGFCAB.DTNEG = (SELECT MAX(TGFCAB.DTNEG) FROM TGFCAB 
WHERE TGFCAB.CODTIPOPER IN (3200, 3205, 3250, 3262)  AND TGFCAB.CODPARC=TGFPAR.CODPARC)