SELECT
AAA.ID,
AAA.CODPARC,
AAA.QTD,
CASE 
WHEN AAA.TIPO IN ('VT','2') THEN AAA.DIAS_CALC
ELSE 0 END AS DIAS_APONT,
AAA.VT_VLR,
AAA.VR_VLR,
AAA.TIPO
FROM
(SELECT
BEN.ID,
BEN.CODPARC,
DIA.QTD,
CASE 
WHEN NVL(APO.DED_ACR,0) = '-' THEN APO.QTD_DIAS * (-1)
ELSE NVL(APO.QTD_DIAS,0) END AS DIAS_CALC,
NVL(PAR.AD_VT_VLR,0) AS VT_VLR,
NVL(PAR.AD_VR_VLR,0) AS VR_VLR,
NVL(APO.TIPO,0) AS TIPO
FROM
AD_BENFUN BEN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = BEN.CODPARC
LEFT JOIN AD_CALBEN CLC ON BEN.ID = CLC.ID
LEFT JOIN (SELECT CLC.ID, COUNT(CAL.DATACALEN) AS QTD
    FROM AD_CALENDARIO CAL, AD_CALBEN CLC
    WHERE CAL.UTIL = 'S' AND TO_CHAR(CAL.DATACALEN, 'mm-yyyy') = CLC.REF 
    AND CLC.ID = '1' /*SUBSTITUIR 1 POR AD_CALBEN.ID*/
    GROUP BY CLC.ID) DIA ON DIA.ID = BEN.ID
LEFT JOIN AD_BENAPO APO ON APO.ID = BEN.ID AND APO.SEQ = BEN.SEQ
WHERE
BEN.ID = '1' /*SUBSTITUIR 1 POR AD_CALBEN.ID*/) AAA
WHERE
AAA.CODPARC = 2425 /*SUBSTITUIR 2425 POR AD_CALBEN.CODPARC*/
