#type.sql#
SELECT
CASE 
WHEN ACT.DIAS > 10 AND ACT.ACT_TOMADA = 'INFORMADO' THEN 'EN'
WHEN AVA.AVALIADO > 0 AND CNT.RESPONDIDO > 0 THEN 'RE'
WHEN AVA.AVALIADO > 0 AND CNT.RESPONDIDO IS NULL THEN 'AV'
ELSE 'AB' END AS STATUS

FROM
AD_REGSAC REG
LEFT JOIN (SELECT
    COUNT(DET.CODPROD) AS AVALIADO,
    DET.ID
    FROM
    AD_DETSAC DET
    WHERE
    DET.AVALIACAO IS NOT NULL
    GROUP BY
    DET.ID) AVA ON AVA.ID = REG.ID
LEFT JOIN (SELECT
    COUNT(CON.ID) AS RESPONDIDO,
    CON.ID
    FROM
    AD_CONTATOS CON
    GROUP BY
    CON.ID) CNT ON CNT.ID = REG.ID
LEFT JOIN (SELECT
    SAC.ID,
    CURRENT_DATE - UCT.DT_CTT AS DIAS,
    CASE
    WHEN UCT.DT_CTT > UAC.DT_ACT THEN 'INFORMADO'
    ELSE 'NAO_REALIZADO' END AS ACT_TOMADA
    FROM
    AD_REGSAC SAC
    LEFT JOIN (SELECT
    MAX(ACT.DT_REG) AS DT_ACT,
    ACT.ID
    FROM
    AD_ACTSAC ACT
    GROUP BY
    ACT.ID) UAC ON SAC.ID = UAC.ID
    LEFT JOIN (SELECT
    MAX(CTT.DH_CONTATO) AS DT_CTT,
    CTT.ID
    FROM
    AD_CONTATOS CTT
    GROUP BY
    CTT.ID) UCT ON SAC.ID = UCT.ID) ACT ON ACT.ID = REG.ID
WHERE
REG.ID = AD_REGSAC.ID


