#type.sql#
SELECT
    CASE
        WHEN STP_GET_CODUSULOGADO() IN (175, 86, 57, 201) THEN NULL
        WHEN CUSTO IS NULL OR CUSTO = '0' THEN 0 
        WHEN CODEMP IN ('2','6') THEN 
            ((VLRNOTA - VLRFRETE - CUSTO - VLRDIF - VLRST - (VLRNOTA * ALIQSN)) / NULLIF(VLRNOTA,0) * 100)
        ELSE 
            ((VLRNOTA - VLRFRETE - CUSTO - VLRIMP) / NULLIF(VLRNOTA,0) * 100)
    END AS MC
FROM (
    SELECT
        CAB.CODEMP,
        CAB.VLRNOTA,
        CAB.VLRFRETE,
        NVL((SELECT SUM(DIN.VALOR + DIN.VLRDIFALDEST + DIN.VLRFCP) 
             FROM TGFDIN DIN 
             WHERE DIN.CODIMP = 2 AND DIN.NUNOTA = CAB.NUNOTA), 0) AS VLRST,
        NVL((SELECT SUM(DIN.VLRDIFALDEST + DIN.VLRFCP) 
             FROM TGFDIN DIN 
             WHERE DIN.CODIMP = 1 AND DIN.NUNOTA = CAB.NUNOTA), 0) AS VLRDIF,
        (SELECT SUM(DIN.VALOR + DIN.VLRDIFALDEST + DIN.VLRFCP) 
         FROM TGFDIN DIN 
         WHERE DIN.NUNOTA = CAB.NUNOTA) AS VLRIMP,
        (SELECT PSN.ALIQUOTA/100 
         FROM TGFPSN PSN 
         WHERE PSN.NUPARTILHA = (SELECT MAX(NUPARTILHA) FROM TGFPSN WHERE TIPOSN = '1')) AS ALIQSN,
        (SELECT SUM(ITE.QTDNEG * CUS.CUSGER)
         FROM TGFITE ITE
         JOIN (
             SELECT CUS.CODPROD, CUS.CONTROLE, CUS.CUSGER
             FROM TGFCUS CUS
             JOIN (
                 SELECT CODPROD, CONTROLE, MAX(DTATUAL) AS DTATUAL
                 FROM TGFCUS
                 GROUP BY CODPROD, CONTROLE
             ) ULT_CUS ON CUS.CODPROD = ULT_CUS.CODPROD 
                       AND CUS.CONTROLE = ULT_CUS.CONTROLE 
                       AND CUS.DTATUAL = ULT_CUS.DTATUAL
         ) CUS ON ITE.CODPROD = CUS.CODPROD AND ITE.CONTROLE = CUS.CONTROLE
         WHERE ITE.NUNOTA = CAB.NUNOTA
        ) AS CUSTO
    FROM TGFCAB CAB
    WHERE CAB.NUNOTA = TGFCAB.NUNOTA
)