#type.sql#
SELECT
DISTINCT(PCR.CONCORRENTE)
FROM
AD_PRCONR PCR
INNER JOIN (SELECT
    MAX(PCR.DTDESCB) AS DTDESCB,
    PCR.CODPROD
    FROM
    AD_PRCONR PCR
    GROUP BY
    PCR.CODPROD) AAA ON AAA.CODPROD = PCR.CODPROD AND AAA.DTDESCB = PCR.DTDESCB
LEFT JOIN (SELECT
    MAX(AAA.CODPROD) AS CODMATRIZ,
    AAA.CODPRODALT AS CODALT
    FROM
    (SELECT
    PAL.CODPROD,
    PAL.CODPRODALT
    FROM
    TGFPAL PAL
    INNER JOIN (SELECT
    PRO.CODPROD
    FROM
    TGFPRO PRO
    WHERE
    PRO.AD_TIP_ALT = 'M') PRO ON PAL.CODPROD = PRO.CODPROD
    UNION ALL
    SELECT
    PRO.CODPROD,
    PRO.CODPROD AS CODPRODALT
    FROM
    TGFPRO PRO
    WHERE
    PRO.AD_TIP_ALT = 'M') AAA
    GROUP BY
    AAA.CODPRODALT) BBB ON BBB.CODMATRIZ = PCR.CODPROD
WHERE
PCR.CODPROD = TGFITE.CODPROD
OR BBB.CODALT = TGFITE.CODPROD
