#type.sql#
SELECT
MAX(AAA.CODPROD) AS CODMATRIZ
FROM
(SELECT
PAL.CODPROD,
PAL.CODPRODALT
FROM
TGFPAL PAL
INNER JOIN (SELECT
PRO.CODPROD
FROM
TGFPRO PRO
WHERE
PRO.AD_TIP_ALT = 'M') PRO ON PAL.CODPROD = PRO.CODPROD
UNION ALL
SELECT
PRO.CODPROD,
PRO.CODPROD AS CODPRODALT
FROM
TGFPRO PRO
WHERE
PRO.AD_TIP_ALT = 'M') AAA
WHERE
AAA.CODPRODALT = TGFITE.CODPROD